### ISSUE TITLE
How to send Data to an Amazon Kinesis Firehose Delivery Stream?

### ISSUE THREAD

**Issue by pchuri** [aws/aws-sdk-unity#100]
Hi there,

I want to send data to kinesis firehose.
Is AWSSDK-Unity Possible?

Please give me a guide.
Thank you.

**Comment by karthiksaligrama** [comment]
At the moment Kinesis Firehose is not supported in Unity. adding it to feature requests

**Comment by karthiksaligrama** [comment]
Added in version 3 for aws sdk for unity.Please raise a new issue on our [dotnet sdk repository](https://github/aws/aws-sdk-net) if you have any other questions
