### ISSUE TITLE
Unity 5.3 has UnityEngine.Logger, please use using Logger = Amazon.Runtime.Internal.Util.Logger;

### ISSUE THREAD

**Issue by AVOlight** [aws/aws-sdk-unity#101]
Unity 5.3 has UnityEngine.Logger please use using Logger = Amazon.Runtime.Internal.Util.Logger;

**Comment by karthiksaligrama** [comment]
unity 5.3 is still in beta and we don't support beta releases at the moment. When we get a release candidate out we will add this feature.

**Comment by michidk** [comment]
Unity 5.3 is now released and has UnityEngine.Logger as metioned above

**Comment by johnnyhoffman** [comment]
Fixed in SDK version 2.1.0.1
