### ISSUE TITLE
AmazonS3Client.PostObjectAsync will never return if the user has no internet connection

### ISSUE THREAD

**Issue by designzoo-peter** [aws/aws-sdk-unity#108]
Tested on iOS, and OSX Editor. The logs show that it recognises that the Status is 0 and it received an error response, but the callback never succeeds. 

If no internet connection is available from the very start, then it is generating [the signed policy for a request](https://github.com/aws/aws-sdk-unity/blob/79545236079607a287afa7fc70baabf5fb8fbf31/Assets/AWSSDK/src/Services/S3/Custom/_unity/AmazonS3Client.unity.cs#L64) that falls over (it gets a response back then nothing happens with the PostAsync call that called for its generation). 

If a signed policy already exists and a PostAsync call is made, then [the UnityMainThreadDispatcher that fails](https://github.com/aws/aws-sdk-unity/blob/79545236079607a287afa7fc70baabf5fb8fbf31/Assets/AWSSDK/src/Core/Amazon.Runtime/Pipeline/_unity/UnityMainThreadDispatcher.cs#L161) to call the callback

The callstack is as follows:

recieved error response
UnityEngine.Debug:Log(Object)
Amazon.Runtime.Internal.Util.UnityDebugLogger:DebugFormat(String, Object[]) (at Assets/AWSSDK/src/Core/Amazon.Runtime/Internal/Util/_unity/UnityDebugLogger.cs:76)
Amazon.Runtime.Internal.Util.Logger:DebugFormat(String, Object[]) (at Assets/AWSSDK/src/Core/Amazon.Runtime/Internal/Util/Logger.cs:189)
Amazon.Runtime.Internal.Transform.UnityWebResponseData:.ctor(WWW) (at Assets/AWSSDK/src/Core/Amazon.Runtime/Internal/Transform/_unity/UnityWebResponseData.cs:67)
Amazon.Runtime.Internal.<InvokeRequest>c__Iterator2:MoveNext() (at Assets/AWSSDK/src/Core/Amazon.Runtime/Pipeline/_unity/UnityMainThreadDispatcher.cs:133)

recieved = Couldn't resolve host 'cognito-identity.eu-west-1.amazonaws.com'
UnityEngine.Debug:Log(Object)
Amazon.Runtime.Internal.Util.UnityDebugLogger:DebugFormat(String, Object[]) (at Assets/AWSSDK/src/Core/Amazon.Runtime/Internal/Util/_unity/UnityDebugLogger.cs:76)
Amazon.Runtime.Internal.Util.Logger:DebugFormat(String, Object[]) (at Assets/AWSSDK/src/Core/Amazon.Runtime/Internal/Util/Logger.cs:189)
Amazon.Runtime.Internal.Transform.UnityWebResponseData:.ctor(WWW) (at Assets/AWSSDK/src/Core/Amazon.Runtime/Internal/Transform/_unity/UnityWebResponseData.cs:68)
Amazon.Runtime.Internal.<InvokeRequest>c__Iterator2:MoveNext() (at Assets/AWSSDK/src/Core/Amazon.Runtime/Pipeline/_unity/UnityMainThreadDispatcher.cs:133)

Status = 0
UnityEngine.Debug:Log(Object)
Amazon.Runtime.Internal.Util.UnityDebugLogger:DebugFormat(String, Object[]) (at Assets/AWSSDK/src/Core/Amazon.Runtime/Internal/Util/_unity/UnityDebugLogger.cs:76)
Amazon.Runtime.Internal.Util.Logger:DebugFormat(String, Object[]) (at Assets/AWSSDK/src/Core/Amazon.Runtime/Internal/Util/Logger.cs:189)
Amazon.Runtime.Internal.Transform.UnityWebResponseData:.ctor(WWW) (at Assets/AWSSDK/src/Core/Amazon.Runtime/Internal/Transform/_unity/UnityWebResponseData.cs:114)
Amazon.Runtime.Internal.<InvokeRequest>c__Iterator2:MoveNext() (at Assets/AWSSDK/src/Core/Amazon.Runtime/Pipeline/_unity/UnityMainThreadDispatcher.cs:133)

Request metrics: {"properties":{"AsyncCall":"False","ServiceName":"Amazon.CognitoIdentity","ServiceEndpoint":"https://cognito-identity.eu-west-1.amazonaws.com/","MethodName":"GetCredentialsForIdentityRequest","RequestSize":"63"},"timings":{"HttpRequestTime":5441.373,"ClientExecuteTime":5458.702},"counters":{}}

And then no callback from the response to the AmazonServiceCallback delegate passed to PostObjectAsync

**Comment by karthiksaligrama** [comment]
also relate to #66 . I'm closing this issue and tracking the progress of the issue there as a general issue for internet connectivity
