### ISSUE TITLE
Flag to stop Debug spam in console

### ISSUE THREAD

**Issue by designzoo-peter** [aws/aws-sdk-unity#109]
There is a lot of stuff being spat out which I have no use for and don't want. Do I have to comment out the print statements in the different Logging classes?

**Comment by designzoo-peter** [comment]
Just noticing the public overrides at the bottom of UnityDebugLogger. I guess I was looking for a more central place that all the possible loggers would share, not just the UnityDebugLogger.

**Comment by johnnyhoffman** [comment]
You can configure logging in awsconfigs.xml, e.g.

```
<logging
    logTo="None" ...
```

or directly in your code, e.g:
```
loggingConfig.LogTo = LoggingOptions.None;
```

**Comment by PLockhart** [comment]
Awesome thanks
