### ISSUE TITLE
Amazon.Unity folder name can cause problems

### ISSUE THREAD

**Issue by benbritten** [aws/aws-sdk-unity#11]
In the AWSCore, CognitoSync and DynamoDB folders there is a subfolder named Amazon.Unity.  Since scene files also have a .unity extension. 

This will throw errors on loading the editor (at least on Mac using 4.6.1p4)

error:
Failed to save scene Assets/Asset Store/AWSUnitySDK/CognitoSync/Amazon.Unity.

The solution is to just change the name of the folder to something else that doesn't end in .unity

**Comment by weijiamao** [comment]
Thanks for reporting this issue. We are working on it. it will be fixed in next release.

**Comment by weijiamao** [comment]
Hi, this issue is fixed in release 1.0.1.
