### ISSUE TITLE
Can't use Cognito in WebGL: no sqlite dll

### ISSUE THREAD

**Issue by skryshi** [aws/aws-sdk-unity#113]
I tried building and running the Cognito demo for Unity WebGL player, and got this error:

"DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found."

Right, there is no sqlite3.dll in the WebGL player. But I assumed the SDK would automatically switch to browser local storage/cookies. It doesn't. Am I missing something? Is there an any easy way to use this SDK for WebGL?

**Comment by karthiksaligrama** [comment]
at this time we are not supporting webgl. tracking this issue in #50

**Comment by skryshi** [comment]
I see :(

Is support for WebGL on your timeline? Any ballpark ETA, like quarter/year? This would help a lot with planning and, honestly, whether to go with AWS or some other service. Thank you!
