### ISSUE TITLE
CognitoAWSCredentials.RemoveLogin do not work.....

### ISSUE THREAD

**Issue by Junhak-Kim** [aws/aws-sdk-unity#114]
When I unlink facebook with identity using RemoveLogin
the identity become unaccessable to identitypool... and  in dashboard the identity is still linked to facebook..
anyone have same issue?

**Comment by turacma** [comment]
Remove login simply removes the login from the local dictionary. If you want to completely disassociate a facebook login from an identity you would need to use the low level [UnlinkIdentity](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSCognitoIdentity.html#//api/name/unlinkIdentity:) method. Note, it is not possible to transition an identity back to unauthenticated; unlinking the Facebook login will cause the identity to become disabled completely.

**Comment by Junhak-Kim** [comment]
Thanks for reply.
