### ISSUE TITLE
SQL data field access

### ISSUE THREAD

**Issue by hgray** [aws/aws-sdk-unity#12]
Would you be open to allowing access to a few more of the fields in the database? In particular, I'm working on managing the timing of syncs to the cloud. If the data was synced within the last x seconds, I will ignore the client request to force a sync.

The database has properties for "last_sync_timestamp", and "last_sync_result". They are not public properties, so can not be checked by my code. The result field seems to actually not be in use, but I'm guessing it will be at some point.

There are probably some other useful fields too, but I'll start with those.

Thanks

**Comment by albertvaka** [comment]
Hello,

You can access most of these fields already through the Metadata field in a Dataset. However, note that the reason they are not accessible directly from the Dataset class is because in case we change the implementation of our Datasets, these fields may disappear or change.

Albert

**Comment by hgray** [comment]
Yup, the metadata fields are a start. I was hoping you could add a few more in there. How much change are you anticipating across the SDK? I realize what we have is a developer release and is subject to change, just curious about when we'll have lockdown and how much flux there is.
Thanks

**Comment by albertvaka** [comment]
I can not give you details about our future plans, as this is done only via official AWS announcements. About the way we store the dataset information, though, I don't see a need for an immediate change.

**Comment by hgray** [comment]
Understood, no worries. In the meantime, please consider making a few more fields public. Thanks!
