### ISSUE TITLE
WWW causes crash with 'large' files on iOS

### ISSUE THREAD

**Issue by designzoo-peter** [aws/aws-sdk-unity#120]
I believe this is a unity issue as a lot of people seem to get it with large WWW uploads/downloads. Can the dev team confirm whether this is an issue? Or can they upload large files successfully on iOS. On iOS the application runs out of memory and crashes when trying to upload files from 15MB to 100MB in size. 

My console shows the following:
Mprotect failed at 0xcd10000 (length 65536) with errno 12
Mprotect remapping failed

I noticed that the recently released [.NET v3](https://github.com/aws/aws-sdk-net/tree/unityv3) branch has moved away from Unity WWW and gone for the native .NET HttpWebRequest, which might go better. If so, maybe it would be worth sticking a note up on the v2 page highlighting the potential issue.
Tested with Unity 5.1.1 and 5.3.1

**Comment by karthiksaligrama** [comment]
We have had couple of people who have similar complaints, but the size really varies on the device make/model itself. Like you said its more of a problem with WWW/Unity rather.

Unity branch in the .NETV3 still uses the WWW (we have not moved away) although at some point we might move to the new UnityWebRequest api in Unity 5.3
