### ISSUE TITLE
OnSyncFailure not returned on main thread?

### ISSUE THREAD

**Issue by antilunchbox** [aws/aws-sdk-unity#124]
OnSyncFailure I get main thread complains, but OnSyncSuccess the same calls are totally fine.

**Comment by johnnyhoffman** [comment]
Hi, can you post the error message you are receiving here?

**Comment by antilunchbox** [comment]
I don't get sync failure all the time, but it's definitely:
"get_isDebugBuild can only be called from the main thread"

**Comment by Andreyul** [comment]
I use `UnityRequestQueue.Instance.ExecuteOnMainThread(action)` as a workaround.

**Comment by johnnyhoffman** [comment]
It makes sense that OnSyncFailure and OnSyncSuccess should be called on the main thread, as is currently not always the case. We will incorporate that into future releases, but for now using ```UnityRequestQueue.Instance.ExecuteOnMainThread``` as @Andreyul mentions is an appropriate workaround.

**Comment by karthiksaligrama** [comment]
Fixed in version 3 for aws sdk for unity. If you continue to face problems please raise a new issue on our [dotnet sdk repository](https://github/aws/aws-sdk-net)
