### ISSUE TITLE
Feature Request: Simple leaderboard?

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-unity#15]
So we're using Cognito as the backend to a player's profile in our game, S3 for storing "ghost" data for levels in our game, I'm sure we'll find a use for DynamoDB somewhere in the mix as well, but I was just wondering if a leaderboard is in your plans as well?

I know there's the https://developer.amazon.com/public/apis/engage/gamecircle stuff, but that seems quite out of date / not maintained and slightly a different project to what you guys are doing, not based off of Cognito identity providers, and all that, so we're reticent to try and shoehorn that in... slightly.

Our game is a racing game and currently we're using our own leaderboard backed by Redis on an EC2 instance to store a person's time on a particular track, then some metadata (cognito userId and timestamp), which we then use to figure out the S3 filename, and pull it down from there, and store locally.  What'd be awesome is if we could ditch that last service that we require to build and maintain ourselves, and use the leaderboard system you have already.

**Comment by albertvaka** [comment]
Hi,

We currently don't have in Amazon Cognito a feature that covers leaderboards' use case, but this feedback helps us prioritize new features in our roadmap, as we are constantly looking to enhance the functionality of Amazon Cognito.

Thank you!

**Comment by seaders** [comment]
No problem Albert, again, thank you for the great product!

The reasoning (if it's at all useful to you) on our side for the request is, basically, our alternatives.  Both Google Play & Apple offer (limited) leaderboards, but both are platform specific, which then messes with our cross platform wants, and motivations.  Facebook offers leaderboards, but that limits it to being logged in with that, only, which messes with our (your) unauthorised options, which is completely more desirable.  And then building our own, backing it with something like Redis (our *current* solution), this means we have to keep open an EC2 instance, but this is our whole reason we want to go the Cognito route, to reduce, or completely eliminate that cost, time and effort.

**Comment by stephenyliu** [comment]
+1

**Comment by Thaina** [comment]
@albertvaka I would like to have arbitrary service for sorting/indexing/ranking table. It would not profit just  game but for many applications. Especially if it integrate in dynamodb which we all used

Currently now dynamodb could sorting by query fantastically. It could used for leaderboard but it just very limited and cannot get index number

**Comment by karthiksaligrama** [comment]
I'm closing this issue as it falls outside the scope of the unity sdk.
