### ISSUE TITLE
Access modifiers

### ISSUE THREAD

**Issue by hgray** [aws/aws-sdk-unity#18]
Would you all mind updating the access modifiers on fields in your virtual, override, and abstract classes so we can override them? For example, if I want to create my own sync manager, I'd likely override the DefaultCognitoSyncManager and override a few methods. I found that I couldn't create an override for OpenOrCreateDataset() because remote, local, cognitoCredentials, and GetIdentityId() are all private. Protected would let me use them.

I'm sure there are other examples too, in places like DefaultDataset and elsewhere.

Thanks.

**Comment by albertvaka** [comment]
Hi,

It seems like a good idea to open these classes a little bit. We will take it into account for our next release.

Thanks,
Albert

**Comment by hgray** [comment]
Great, thanks very much!

**Comment by albertvaka** [comment]
We just released a new version that includes this changes.

Thanks for your comments!

**Comment by hgray** [comment]
You guys are the best, thanks!
