### ISSUE TITLE
Table.Query problem. 

### ISSUE THREAD

**Issue by thewall01210** [aws/aws-sdk-unity#2]
I'm currently working on an iOS app in Unity, and querying a table for messages.  When I query the table the first time, the search that is returned by Table.Query is valid, and all the appropriate results are returned.  The second time I call Table.Query, your logging does not show that a WWW request has been made or completed.  Nothing is returned and search.Count does not contain a value.  I am not using the async version of the call, and I'm executing the request inside of a thread. 

Some things to note: I'm using Search.Count as a loop condition instead of Search.IsDone, since the loop would execute too many times when I was using the async version of query.  In addition to this I had been using ThreadPool.QueueUserWorkItem to execute the search, but had moved it to its own dedicated thread for testing purposes. 

`
void GetMessage(object prefix)
{
		var filter = new QueryFilter(MESSAGE_PREFIX_KEY, QueryOperator.Equal, prefix.ToString());
		_teamMessageData.Clear();

		Search search = null;
		try
		{
			search = _teamMessages.Query(filter);
		}
		catch(Exception ex)
		{
			Debug.LogException(ex);
		}

		if(search == null)
		{
			Debug.Log("returnning null");
			return;
		}
		
		Debug.Log("SearchCount: " + search.Count);
		while(_teamMessageData.Count != search.Count)
		{
			if(search.Count < 1)
				break;

			_teamMessageData.AddRange(search.GetNextSet());
		}

		_processTeamMessages = true;
		search.Reset();
}
`

**Comment by weijiamao** [comment]
Hi, we could not reproduce the issue. However, following the steps described below may help you find the root cause.

1. Make sure the logging is enabled: Put `AmazonLogging.EnableSDKLogging = true;` in `Start();`
2. Try Sample code at `/SampleCode/DynamoDB/AmazonMiddleLevelQueryAndScan`. The method `FindRepliesInLast15Days` is doing a similar thing with your code snippet. Before you run the sample code, create a table called **Reply** with String hash attribute name **Id**.
3. Set a breakpoint at `filter`. Make sure, `filter` and `_teamMessages` have the same value in the second table query.

**Comment by thewall01210** [comment]
Hey, thanks for the suggestions.  I am, however, a little confused by what you mean by making sure `filter` and `_teamMessages` have the same value as `filter` is of type Filter and `_teamMessages` is of type Table.  Does `_teamMessages` get assigned the filter variable when Table.Query is called? Also, is it possible that `_teamMessages` is losing its value between the first and second query?

**Comment by weijiamao** [comment]
We assume `filter` and `_teamMessages` are same in two queries. From your description, it seems WWW is not called in second query. It's possible that those variables are accidentally overwritten.

**Comment by thewall01210** [comment]
To address all of your suggestions, we have had `AmazonLogging.EnableSDKLogging = true;` thats how we were able to find out that the WWW requests were not being called.  We have modeled our query function off of the query function in the samples, and I don't believe the problem lies with the `filter` or `_teamMessage` variables.  After calling `Table.Query` `LoadAsync<T>` no longer works either. By this i mean it does not trigger its callback function.  I have even tried using `LoadAsync<T>` on a completely different table and received the same result.

**Comment by thewall01210** [comment]
We were able to find the source of the issue.  If you make too many calls to `LoadAsync<T>` on iOS it spawns a bunch of threads and does not close them, making it impossible to create anymore threads when making database calls.  I don't know if this is how iOS handles threads or how your thread dispatcher handles things, but that was the issue.  Thanks, for your patience and feedback.

**Comment by weijiamao** [comment]
Thanks for your feedback ! We will dive deeper on this issue.
