### ISSUE TITLE
Cleaning up where files land from unitypackages

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-unity#23]
We've a number of plugins and it's been a bit hectic to know *exactly* what plugin every file belongs to, and also keep sanity to the files structure.  The specific egregious ones currently are those that go in to the Assets/ root, License.txt, Notice.txt and link.xml.  Each one of these files are named incredibly generically, and if another plugin comes along with License.txt, Notice.txt and link.xml, if any of those files are needed for this SDK to operate (functionally, or legally), they would be instantly overwritten.

With the license and notice, I know I can safely move them in to Assets/AWSUnitySDK/ (which imo is where they should live anyway, and still every other time I install a unitypackage, they come back).  But with link.xml I don't actually know.  I don't have a full understanding of exactly what this file does, nor where is it safe to be moved to.

I'm reaching out to every plugin creator, and Unity themselves to try get a more mature setup to where unitypackages place files, and thinking about a Upgrade system for them.  If you place in version 1.0.1, a necessary file in Assets/, but it's no longer needed in 1.0.2, I have to remember that that file *used* belong to 1.0.1, but can be safely deleted, but more than likely that's not going to happen, and that redundant file will just be left over.  Same for if I want to uninstall the plugin.  If everything's within a properly named sub-folder (your AWSUnitySDK folder is a *perfect* example of this), all of this is sorted out, and is a better setup for all.

**Comment by weijiamao** [comment]
We try yo keep every source file has Amazon prefix and all code be under Asset/AWSUnitySDK and Asset/AWSUnitySDKSample. 

We don't have link.xml file. Maybe it's a file from other plugin. But please double check it and let me know if I am wrong.

**Comment by seaders** [comment]
*sigh* you're right, it's from UnityAds, but came in with the same git commit as the Amazon SDK, so that was my mistake.

File content was just 

	<linker>
		<assembly fullname="UnityEngine">
			<type fullname="UnityEngine.WWW" preserve="all" />
		</assembly>
	</linker>

So trying to figure out what it belongs to was... difficult.  This is exactly my problem with plugins, and can't understand how Unity didn't foresee this, and the issues that came with it...

The License.txt and Notice.txt go in at root though.  If you can't set them to go into Asset/AWSUnitySDK (which if you can't, I'll be moving them, anyway), please do at least prefix them so they're identifiable as attached to AWSUnitySDK.

Again, it's not just you guys I'm making this request to.  We've got Facebook, Google Play, Unity Ads, and MAT official unity plugins, and NeatPlug Flurry and Prime31 Activity Sharing System plugins... Each one of them have a (seemingly) unique weird and wonderful way of where they leave their files, and trying to manage that, while also making sure they don't break themselves, or others, is... fairly time consuming and difficult.

**Comment by karthiksaligrama** [comment]
from 2.0.0.0 we've moved all the files in the AWSSDK folder including examples, source and editor scripts. Only plugins are outside.
