### ISSUE TITLE
feature: sign v4 example of POST

### ISSUE THREAD

**Issue by chbfiv** [aws/aws-sdk-unity#25]
http://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html

it would be nice if you could provide an example of a simple REST call using Sign v4 so we can call other API's not defined here. Ideally, the SDK could provide a minimal footprint for this so we don't bloat the games with all these extras (so we could delete features we dont want)

**Comment by weijiamao** [comment]
Hi, can you share more information about what REST API you would call ?

**Comment by chbfiv** [comment]
initially analytics and kinesis. Mainly the concern is how heavy your SDK is. It would be ideal that credentials be independent from all the other services your providing as an SDK. If nothing else, providing examples of how to sig requests for using aws services so we can handle the api calls as needed. (maybe just point out there to look in the existing SDK with some documentation on the flow)

**Comment by karthiksaligrama** [comment]
We just launched Mobile analytics last week. Did you get a chance to try that? AWS SDK for unity is still in developer preview & we appreciate your feedback on how we can improve the sdk. The sdk is modularized, so you can only include those services and delete the others from the sdk.

As per Signature you can have a look at https://github.com/aws/aws-sdk-unity/tree/master/Assets/AWSUnitySDK/AWSCore/Amazon.Runtime/Internal/Auth It has the signature implementation for various services.
