### ISSUE TITLE
Support HTTPS for S3 posts

### ISSUE THREAD

**Issue by jeremyburgesstm** [aws/aws-sdk-unity#26]
Hi,

We're looking at using S3 directly from our Unity clients, and functionally the code I've written works fine, except that it fails to post when behind certain proxies (such as our work one!). 

A simple way to avoid this problem in many cases is to support HTTPS for S3 posts. To confirm this works I've hardcoded it in, and it works fine. If necessary I can make a pull request for you with a full end to end code change, but I'm not sure how you'd want this functionality to be exposed.

Many thanks,
Jeremy

**Comment by weijiamao** [comment]
Thank you for reporting this issue. By default we should use HTTPS for all s3 end points. By some reason, now we use HTTP for us-east-1(all other end points by default still using HTTPS). We will fix this issue in next release.

**Comment by jeremyburgesstm** [comment]
Hi,

For sure - that would be good to be fixed, but the issue I was specifically referring to is the hardcoded usage of 'http' inside the ProcessS3PostRequest method in AmazonWebServiceClient (AmazonWebServiceClient.s3.cs). The URLs for posts are simply hardcoded to use HTTP rather than using the mechanism you're using elsewhere to determine whether to use HTTP or HTTPS. This code means that all S3 posts specifically use HTTP irrespective of which region is being used (our S3 Buckets are actually in US-West-2).

Cheers,
Jeremy

**Comment by weijiamao** [comment]
Yes, thanks for pointing it out. We will also fix this POST issue in next release.

**Comment by karthiksaligrama** [comment]
Hi,
We have released a new version of the sdk for unity v1.0.4 which has a fix for this bug.
