### ISSUE TITLE
Can we assign client_id to analytics requests?

### ISSUE THREAD

**Issue by zeroc** [aws/aws-sdk-unity#29]
We would like to track users based on user id within our game.
How can we assign a client_id just as in rest api?
http://docs.aws.amazon.com/mobileanalytics/latest/ug/PutEvents.html

Thank you.

**Comment by weijiamao** [comment]
Can you share more information about your use case ? 
Now there is only one client id for the application. Would you have multiple client ids in one application ?

**Comment by weijiamao** [comment]
At first time app launch, mobile analytics client would generate a random unique identifier for you as client id and then, cache the identifier for later use. Do you have the user id defined by yourself ?

**Comment by zeroc** [comment]
Yes, each player in our game has a unique user id.
We would like to use that user id as the client id to identify the user.

**Comment by weijiamao** [comment]
Hi, just double check: do you have the use case that using more than one client id in your app?  For example, you would create two MobileAnalyticsManger instances with different client id.

**Comment by zeroc** [comment]
The use case is that we would like to specify client_id, other than a generated random identifier.

Thank you.

**Comment by weijiamao** [comment]
All right. We are working on this and will add it in next release.

**Comment by karthiksaligrama** [comment]
Hi,
We have released a new version of the sdk for unity (v1.0.4) which allows you to specify custom client_id's. Please update and let us know if you have any feedback.
