### ISSUE TITLE
SynchronizeOnConnectivity()

### ISSUE THREAD

**Issue by Claytonious** [aws/aws-sdk-unity#3]
The implementation of this method is simply:

throw new NotImplementedException();

:-(

Is this on the roadmap to actually implement?

Thanks!

**Comment by weijiamao** [comment]
Thank you for bringing this up. This is on our backlog and we will address this in the up coming releases. Please note that as the SDK is currently in Developer Preview, there may be missing features. Your feedback will help us prioritize.

**Comment by albertvaka** [comment]
Hi,

We released a new version of the SDK (1.0.1) with an implementation of SynchronizeOnConnectivity. I hope it helps :)

Albert
