### ISSUE TITLE
No way to specify a global secondary index on a scan?

### ISSUE THREAD

**Issue by aaronhoogstraten** [aws/aws-sdk-unity#31]
I'm trying to use a ScanRequest with AmazonDynamoDBClient.ScanAsync() but there's no IndexName property as there is in a QueryRequest object. http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html#GSI.Scanning says that you should be able to do a GSI scan with the Scan API. Is this not implemented yet?

**Comment by weijiamao** [comment]
Hi, thank you for your feedback. It's not implemented yet. Current DynamoDB client is not update-to-date. We are working on it and make sure it will contain all DynamoDB features.

**Comment by aaronhoogstraten** [comment]
Thanks for the response. Is there a list somewhere to let us know the completion state of DynamoDB client? It would be much easier to reference then attempting to cross reference the normal .NET API with the code we have.

**Comment by weijiamao** [comment]
So far we don't have the list. New client will keep updated like .NET DynamoDB client.
