### ISSUE TITLE
QueryRequest.QueryFilter not working?

### ISSUE THREAD

**Issue by aaronhoogstraten** [aws/aws-sdk-unity#32]
I attempted to use 
`queryRequest.QueryFilter.Add("IsActive", new Condition { AttributeValueList = { new AttributeValue { N = "1" } }, ComparisonOperator = ComparisonOperator.EQ });`
but get a 400 Bad Request Response back. I'm using this on a global secondary index query with TableName, IndexName and KeyCondition specified. "IsActive" is a projected attribute on my GSI. I'm using the QueryRequest with `AmazonDynamoDBClient.QueryAsync()`. It works when I comment out my QueryFilter line.

**Comment by weijiamao** [comment]
Hi, can you use curl command to get the failure reason ?

**Comment by aaronhoogstraten** [comment]
I just commented in my QueryFilter line again and it appears to be working now? I don't believe anything changed on my end, but it's properly filtering on my "IsActive" attribute now so thanks!
