### ISSUE TITLE
Where is the mapped class for Cognito (like DynamoDB has), and what should we do if no connection initially?

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-unity#33]
In the developer guide for DynamoDB for .NET, http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ArbitraryDataMappingHLAPI.html, you're able to create a mapped DynamoDB class incredibly easily like,

    [DynamoDBTable("ProductCatalog")]
    public class Book
    {
        [DynamoDBHashKey]   // hash key
        public int Id { get; set; }

        [DynamoDBProperty]
        public string Title { get; set; }

        [DynamoDBProperty]
        public string ISBN { get; set; }
        // Multi-valued (set type) attribute. 

        [DynamoDBProperty("Authors")]
        public List<string> BookAuthors { get; set; }

        // Arbitrary type, with a converter to map it to DynamoDB type.
        [DynamoDBProperty(typeof(DimensionTypeConverter))]
        public DimensionType Dimensions { get; set; }
    }

Which, while incredibly useful for DynamoDB, to me, that would make a whole lot more sense for a Cognito backed class, something like,

    [CognitoDataset("ProductCatalog")]
    public class Book
    {
        [CognitoProperty]
        public int Id { get; set; }

        [CognitoProperty]
        public string Title { get; set; }

        [CognitoProperty]
        public string ISBN { get; set; }
        // Multi-valued (set type) attribute. 

        [CognitoProperty("Authors")]
        public List<string> BookAuthors { get; set; }

        // Arbitrary type, with a converter to map it to DynamoDB type.
        [CognitoProperty(typeof(DimensionTypeConverter))]
        public DimensionType Dimensions { get; set; }
    }

Or similar.  Reason I'm saying this is because I've basically written a kind of custom version of this already, because I didn't think this existed within your SDK already, but seeing it for DynamoDB, but not Cognito doesn't make a whole lot of sense to me.

And my second question.  In testing, if you turn off network connectivity the very first time, you don't have access to a Dataset to store anything.  We plan on having a Cognito Dataset as the complete backend of a user's profile, whether they're online, or offline (obviously they can only sync when online), but I'm completely confused as to what to do if they don't have a network connection the very first time they launch the app, before they've even a cached cognito id.

**Comment by weijiamao** [comment]
Yes, the similar feature is not in Cognito now. Thank you for your feedback. Your suggestion does help us prioritize our work. We are considering this feature.

**Comment by karthiksaligrama** [comment]
Moved to feature requests https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
