### ISSUE TITLE
version 1.04 compile errors on iOS with Unity 5.0.1p4

### ISSUE THREAD

**Issue by benbritten** [aws/aws-sdk-unity#38]
In AmazonHookedPlatformInfo:

starting at line 275:

            if(iPhone.generation.ToString().StartsWith("iPhone"))
            {
                Model = "iPhone";
            }
            else if (iPhone.generation.ToString().StartsWith("iPad"))
            {
                Model = "iPad";
            }
            else
            {
                Model = "iPod";
            }

generates this error at build time:

Assets/Asset Store/AWSUnitySDK_1.04/AWSCore/Amazon.Unity3D/AmazonHookedPlatformInfo.cs(275,16): error CS0103: The name `iPhone' does not exist in the current context

It is now Device.generation (in UnityEngine.iOS).

Putting that in seems to fix the problem.

**Comment by karthiksaligrama** [comment]
Hi,

Thank you, We are aware of some of the problems with the unity 5.0 and we are working towards making the sdk compatible.

**Comment by benbritten** [comment]
No worries.

note this still exists in 1.05
Adding:
using UnityEngine.iOS;

and changing iPhone.generation to Device.generation fixes it.

**Comment by karthiksaligrama** [comment]
Fixed in V 2.0.0.0
