### ISSUE TITLE
Null reference in ProcessHttpResponse

### ISSUE THREAD

**Issue by MHopke** [aws/aws-sdk-unity#4]
Hi again,

I just wanted to let you know, it is sometimes possible for AmazonWebServiceClient's ProcessHttpResponse to have a null asyncResult which can cause the app to crash on iOS. So for anyone who has the issue, put an null check around it like so:

```
if (asyncResult != null)
{
    asyncResult.IsCompleted = true;
    asyncResult.InvokeCallback();
}
```

**Comment by weijiamao** [comment]
We can guarantee it would not happen. Please check [here] (https://github.com/aws/aws-sdk-unity/blob/397cd4ea25b3f1243bc218dae40f539e5506771d/Assets/AWSUnitySDK/AWSCore/Amazon.Unity/AmazonMainThreadDispatcher.cs#L149).

            if (result != null)
            {
                ...
                ThreadPool.QueueUserWorkItem (result.WaitCallback, (object)result);
            }
