### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by NeoAnderson87** [aws/aws-sdk-unity#44]
Hello , I am getting this issue:
on Synchronize () or RefreshDatasetMetadataAsync() we get the a 403 Forbidden Error.

"WebException: 403 Forbidden
Rethrow as AmazonServiceException: 403 Forbidden
Rethrow as DataStorageException: Failed to list records in dataset: Account"

Unity:4.6.3f1
Os:Windows 8.1 pro

And this is my curl response:
{"message":"The request signature we calculated does not match the signature you
provided. Check your AWS Secret Access Key and signing method. Consult the serv
ice documentation for details.\n\nThe Canonical String for this request should h
ave been\n'GET\n/identitypools/us-east-1%3Adddbd6ae-e9ae-4be7-a385-f0c44a279f22/
identities/us-east-1%3A67aa6ec6-310c-4f0c-9a15-d01406580d68/datasets/PlayerInfo/
records\nlastSyncCount=0\nhost:cognito-sync.us-east-1.amazonaws.com\nuser-agent:
AWS-SDK-UNITY/1.0.5\nx-amz-content-sha256:44136fa355b3678a1146ad16f7e8649e94fb4f
c21fe77e8310c060f61caaff8a\nx-amz-date:20150410T101458Z\nx-amz-security-token:AQ
oDYXdzEFsa4ARMSNIsJwPdpxCJ00lrSg5uqgQHOdvQk8l496BnNO639LL9UMK1Q7342h+SVKJoSITh70
2/eaOUMaRUMx94JNLNKm0X1YcN84lQm54bUrw9xp3Y4Nf0AfXqx6SGtPsZtl85vn7+eqE+/AdVXdaaLM
3Iod5KxbI4UW2/s10AX5YDYpDhR/MnafMzytBePO8rSJQJYPx16TS8Crs08gkDIB+RBwmMsj2y0nWvQb
s1fF0ELTnhSVgyWvRtnAjbMXPkk0hfHfptlyDaV94gPg39zuWzHXN4LYkwsrjsw8lFzLKDhSwf37Se2Z
3u0XrO5+OnWV9xP4yHInxcJNyy5MV+n6Fjc3UR4KX1uV3X45rO4g6p6dOWVTwwRo55CwFEsi73W5elOK
NjWAG+CZxyza/nC7dVysjEiFyxN+k2sjMsw2k6kiKe7/8qdbP9sVmghE8VDKDfL+5cvgBwnANo+ptwQY
6G6ING0+0YATxJpB8M4rPm14rkvtzJuJU9E578dt0Pc18H+aR/gqsro6o9LoNpq0ly12fgWWlPMy5xZB
3Q0mnakJPzGPVlKakwv3e1DEoboFEtGs8ZYyBMAH9GmK+OQb7QW9KP2grdMuoH87RA8s0HyO1gh6lYYv
k86ypcGzwJyrZm8zfCjARFApHQ6HWoT0Pwz8ekw0geMLZnDF5eVtxa8ffsi+5AwZLW6qM6Fm4PhwfD4D
CGNrx2uhcT5tXhy14z0DGuqHk5NweKdkwOQcnXUj6rekk1/MPghH7UBfhaauXtT8F9vMV2cR+caZl/u5
GasF0VZLtA4QgKgAuxcbqU2SDgvp6pBQ==\nx-http-method-override:GET\n\nhost;user-agen
t;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-http-method-override\n4
37da515a768a74bdc5d9c67803dfe8e3f0339ebad2e87474f5d3fde0427bd80'\n\nThe String-t
o-Sign should have been\n'AWS4-HMAC-SHA256\n20150410T101458Z\n20150410/us-east-1
/cognito-sync/aws4_request\n39571a63dd507046bd6019cd89951dc7ba615e980a3068f0f73e
1788d025b81e'\n"}

NOTE: This happens only for Auth users( i am using Facebook auth) .. for guest users (unauth) it works fine.

**Comment by weijiamao** [comment]
Can you double check that you have added facebook app id in identity pool setting ?
You can go to AWS Console and then click the identity pool. Choose "Edit identity pool". Go to setting "Public identity providers " and then check "Facebook App ID".

**Comment by NeoAnderson87** [comment]
Yes,it's there! Also on identity pool dashboard I am able to see number of facebook logins that have occured , only when I try to sync or RefreshDatasetMetadata then i get the above mentioned error.And hence the identities with linked fb logins have no dataset
![screen shot 2015-04-15 at 2 15 50 pm](https://cloud.githubusercontent.com/assets/8350713/7155159/0508af04-e37a-11e4-8a20-6d8a6b45c0de.png)
.

**Comment by rachitdhall** [comment]
Can you please clear your cache and try syncing the dataset? Also it will be helpful if you can post your curl request parameters (masked are fine).

**Comment by karthiksaligrama** [comment]
Assuming fixed. Closing issue. Please reopen if otherwise.
