### ISSUE TITLE
Can't change user login after the Credentials have been initiated once! 

### ISSUE THREAD

**Issue by NeoAnderson87** [aws/aws-sdk-unity#45]
In a scenario where CognitoAWSCredentials has been initialized and after that a user logs in using public auth like facebook , IdentityProvider.RefreshAsync doesn't actually changes the identity as there is a check " if (!IsIdentitySet) " in refresh async override function in AmazonCognitoEnhancedIdentityProvider , which stops in getting the identity linked to that particular FB account.

**Comment by karthiksaligrama** [comment]
When the logins map is updated we clear the credentials. Clearing the credentials forces GetCredentials from the service. As a part of the response for the get credentials we also get the identity id which we use to update the local cache.

**Comment by NeoAnderson87** [comment]
I am attaching my code here.

	public static void FacebookLoginCallback(FBResult result)
	{
		if (result.Error != null || !FB.IsLoggedIn)
		{
			Debug.LogError(result.Error);
		}
		else
		{
			
			CognitoAWSCredentialsInstance.IdentityProvider.Logins.Add("graph.facebook.com",FB.AccessToken);

			CognitoAWSCredentialsInstance.IdentityProvider.RefreshAsync(AuthenticationCallback, "Facebook Login",true);
		}
	}

	This leads the call to RefreshAsync in AmazonCognitoEnhancedIdentityProvider

	public override void RefreshAsync(AmazonServiceCallback callback, object state)
		{
            //_token = null;
            AmazonServiceResult voidResult = new AmazonServiceResult(null, state);
            if (!IsIdentitySet) //And here as I mentioned IsIdentitySet is true
            {
                var getIdRequest = new GetIdRequest
                {
                    AccountId = null,
                    IdentityPoolId = IdentityPoolId,
                    Logins = Logins
                };

    Here since the IsIdentitySet is true I never get the identity linked with my fb account.
    Do I have to call ClearCredentials myself?

**Comment by karthiksaligrama** [comment]
ok i see the source of confusion. Looks like the Logins dictionary has a public settter in the identity provider. and we have deprecated all the methods with it but not deprecated the property itself. 

Please use Credentials.AddLogins to set your logins dictionarty. It has clear credentials implemented.

**Comment by karthiksaligrama** [comment]
Assuming this fixes your problem. Closing this issue. Please reopen if you feel otherwise
