### ISSUE TITLE
Geospatial Indexing support in Unity SDK?

### ISSUE THREAD

**Issue by flyingaudio** [aws/aws-sdk-unity#46]
We need a backend that can store geo points with an object and then query objects based on that data. It sounds like geospatial indexing is the AWS solution for this.  It this possible with the Unity SDK?  If not, will it be added soon?

This is a critical piece, in our consideration of AWS.

**Comment by karthiksaligrama** [comment]
Hi,

Geo Library is a server side java library which can run on an AWS Elastic Beanstalk and uses dynamodb as a backend. Please refer https://github.com/awslabs/dynamodb-geo for more information on the library and refer readme on how to setup and run the sample server app. I would also suggest you read up on [limitations](https://github.com/awslabs/dynamodb-geo#limitations) on read me of the library 

For the client side there is no sdk support available. But you can do something like 

```
Dictionary<string,object> requestDictionary = new Dictionary<string,object>();
                        requestDictionary.Add("action","query-radius");
Dictionary<string,object> request = new Dictionary<string, object>();
request.Add("lat",<latitude>);
request.Add("long",<longitude> );
request.Add("radiusInMeter",<radiusinMeter>);
requestDictionary.Add("request",request);
            
string jsonRequest = JsonMapper.toJson(requestDictionary);
byte[] postBody = System.Text.UTF8Encoding.UTF8.GetBytes(jsonRequest);
UnityEngine.WWW wwwrequest  = new UnityEngine.WWW(<url-SecurityToken-elastic-beanstalk>,postBody);
yield wwwrequest;
```   

In Addition to this, AWS RDS (using PostgreSQL & PostGIS extension) & AWS CloudSearch also have Geospatial Indexing support. You can read more about it [here](http://docs.aws.amazon.com/cloudsearch/latest/developerguide/searching-locations.html).

**Comment by karthiksaligrama** [comment]
Assuming the question is answered. Closing this issue. Please reopen if you need more clarification.
