### ISSUE TITLE
Lambda Support

### ISSUE THREAD

**Issue by rtroxell** [aws/aws-sdk-unity#47]
It would be great to have Lambda support in the Unity SDK. In particular, I'd like to use Lambda's "request-response" model along with a Cognito identity.

**Comment by karthiksaligrama** [comment]
Thank you for the feedback. This will help us prioritize the services.

**Comment by seaders** [comment]
Yeah, this would really be great if this were added to Unity, as we're using the "Building a Mobile Backend Using AWS Lambda", https://mobile.awsblog.com/post/Tx1OUIR0XJAI3ZM/Building-a-Mobile-Backend-Using-AWS-Lambda, and that's *obviously* incredibly difficult to do, if we can't run a lambda call from the devices.

I'm currently in the process of running a low-level raw call from our app, but that's obviously proving a pain.  The fact that Lambda's just gone through a big release, and the library is on the .NET, iOS, Android, Javascript, Java, PHP and Python platforms... it does feel like we're a wee bit behind :(

**Comment by seaders** [comment]
Hey rtroxell, I've actually taken, and brought in the Invoke function from the Lambda API in the .NET SDK.  It had to be changed a little bit from how they do things in the .NET SDK to how things work here, but I've tested (in the Editor, and on iOS and Android) and brought it in to our project fully now.

You can find it where we've (SixMinute) forked this -> https://github.com/SixMinute/aws-sdk-unity and be aware I've *only* done the Invoke function, as I don't need anything else, but realistically it only took me a little while, so if you need any more, it shouldn't take you too long to bring them in yourself from the .NET.

Don't really understand why there's a delay from AWS themselves though... if the .NET library is as up to date with the rest of the libraries, I don't see why the Unity one can't be too :unamused: .

**Comment by karthiksaligrama** [comment]
closed in 2.1.0.0
