### ISSUE TITLE
When will amazon mobile analytics be available to unity sdk?

### ISSUE THREAD

**Issue by zeroc** [aws/aws-sdk-unity#5]
Hi,

We are currently looking into mobile analytics for unity.
Could you shed some light on this issue?
Thank you.

**Comment by Mudeem** [comment]
Thank you for writing to us. We are actively working on adding Mobile Analytics service in the Unity SDK. We will update this thread once it is available.

**Comment by zeroc** [comment]
Thanks for the fast response.
Is it possibly available in one month?
We are very interested in trying it out, and willing to help testing it, even alpha version.
Thank you!

**Comment by Mudeem** [comment]
Thanks you for the offer to help test the Analytics functionality. If possible, please provide a direct email address where we can reach you.

**Comment by zeroc** [comment]
Thank you.
My email is max@ocous.com

**Comment by seaders** [comment]
FYI, if you're looking for any more testers, we'd love to get in on the act as well.  We had Analytics all up and running for our last game in Adobe AIR.

**Comment by Auralien** [comment]
Hi guys! At the moment we are working on a game in Unity and we are determined to use your mobile analytics for it. Do you have any updates concerning Amazon Mobile Analytics support in AWS Mobile SDK for Unity? :) If you are looking for more testers I would be happy to help, just let me know!

**Comment by jmglov** [comment]
@Mudeem I hacked together something that uses the [AmazonWebServiceClient](https://github.com/aws/aws-sdk-unity/blob/master/Assets/AWSUnitySDK/AWSCore/Amazon.Runtime/AmazonWebServiceClient.cs) plumbing to make requests. My marshalling is a NOOP for now, but I have it doing the basic Cognito auth, then firing off a POST to the proper endpoint.

I plan to keep working on it, but I figured I'd drop a Gist here in case anyone has any comments. Especially comments such as "what are you thinking!?", and especially if said comments go on to tell me what I should be thinking. ;)

https://gist.github.com/jmglov/c8cf2ef268dede96ca69

**Comment by Mudeem** [comment]
AWS Mobile SDK for Unity now support Amazon Mobile Analytics. Please see the blog post for details: http://mobile.awsblog.com/post/Tx3E8EFREHR4JV8/Announcing-Amazon-Mobile-Analytics-in-the-AWS-Mobile-SDK-for-Unity

**Comment by jmglov** [comment]
I'm commenting just in case anyone else runs into a "Ran out of trampolines of type 2" error on iOS. Apparently, C# code that makes heavy use of generics uses lots of [Mono trampolines](http://www.mono-project.com/docs/advanced/runtime/docs/trampolines/). We were already using [Json.Net](http://www.newtonsoft.com/json) and [websocket-sharp](https://github.com/sta/websocket-sharp), and apparently the AWS SDK pushed us over the limit.

The solution is to add `nimt-trampolines=512` to AOT options in iOS > Player Settings > Other Settings, as detailed here:

http://answers.unity3d.com/questions/64909/ran-out-of-trampolines-of-type-2-ios.html
