### ISSUE TITLE
sqlite3 not found

### ISSUE THREAD

**Issue by dan335** [aws/aws-sdk-unity#52]
I'm getting this error.

	DllNotFoundException: sqlite3
	Amazon.Unity3D.Storage.SQLiteDatabase..ctor (System.String dbPath) (at Assets/AWSUnitySDK/AWSCore/Amazon.Unity3D/Storage/SQLiteDatabase.cs:159)
	Amazon.Unity3D.Storage.SQLiteKVStore.SetupDatabase (System.String dataPath) (at Assets/AWSUnitySDK/AWSCore/Amazon.Unity3D/Storage/SQLiteKVStore.cs:43)
	Amazon.Unity3D.Storage.SQLiteKVStore..cctor () (at Assets/AWSUnitySDK/AWSCore/Amazon.Unity3D/Storage/SQLiteKVStore.cs:28)
	Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Amazon.Unity3D.Storage.SQLiteKVStore
	Amazon.CognitoIdentity.CognitoAWSCredentials..ctor (System.String unAuthRoleArn, System.String authRoleArn, Amazon.CognitoIdentity.AbstractCognitoIdentityProvider cibClient, IAmazonSecurityTokenService stsClient) (at Assets/AWSUnitySDK/AWSCore/Amazon.CognitoIdentity/CognitoAWSCredentials.cs:138)
	Amazon.CognitoIdentity.CognitoAWSCredentials..ctor (System.String identityPoolId, Amazon.RegionEndpoint region)
	CognitoSyncClientManager.init () (at Assets/aws/CognitoSyncClientManager.cs:46)

Using unity 5 and windows 8.

**Comment by karthiksaligrama** [comment]
This is the known issue in Unity 5. We are working on a fix for it.

**Comment by karthiksaligrama** [comment]
Fixed in V 2.0.0.0
