### ISSUE TITLE
JIT runtime issue with AWS in assemblies

### ISSUE THREAD

**Issue by hgray** [aws/aws-sdk-unity#53]
The way event handlers are set up in the AWS code is incompatible with AOT platforms when compiled in assemblies. For example, in AWSConfigs, there is an event for property changed:
//
internal static event PropertyChangedEventHandler PropertyChanged;
        internal const string LoggingDestinationProperty = "LogTo";
        internal static void OnPropertyChanged(string name)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null)
            {
                handler(null, new PropertyChangedEventArgs(name));
            }
}
//

Running this code results in the following exception:
System.ExecutionEngineException: Attempting to JIT compile method '(wrapper managed-to-native) System.Threading.Interlocked:CompareExchange (System.ComponentModel.PropertyChangedEventHandler&,System.ComponentModel.PropertyChangedEventHandler,System.ComponentModel.PropertyChangedEventHandler)' while running with --aot-only.

To support AOT platforms, it is recommend to use the add/remove methods of an event handler:
//
internal static PropertyChangedEventHandler _propertyChangedListeners;
internal static event PropertyChangedEventHandler PropertyChanged{
		add{
			_propertyChangedListeners+=value;
		}
		remove{
			_propertyChangedListeners-=value;
		}
}

internal static void OnPropertyChanged(string name)
		{
			if (name == null)
				return;
			
			if (_propertyChangedListeners == null)
				return;
			
			Delegate [] listeners = null ;
			
			lock(_propertyChangedListeners) {
				// get the listeners
				listeners = _propertyChangedListeners.GetInvocationList() ;
			}
			if (listeners != null) {
				foreach (Delegate listener in listeners) {
					try {
						listener.DynamicInvoke (new PropertyChangedEventArgs (name));
					}  catch (Exception e) {
						Debug.WriteLine ("Event Listener Exception: " + e.ToString ());
					}
				}
			}
}
//

**Comment by karthiksaligrama** [comment]
Thank you for the feedback, We will update you once we have a fix.

**Comment by hgray** [comment]
I'm looking into the possibility of cross assembly issues as some of the other events with the same signature are not having an issue. The delegate for this particular event is coming from System.ComponentModel.

**Comment by hgray** [comment]
It seems to not be specific to cross assembly access. I am tracking 10 or so event handlers which cause JIT issues when the Amazon code is compiled to its own assemblies.

**Comment by karthiksaligrama** [comment]
Please take a look at https://github.com/aws/aws-sdk-net/tree/unityv3 and our blog post http://mobile.awsblog.com/post/Tx1K3R5975IFX8/AWS-SDK-for-Unity-Is-Now-Part-of-AWS-SDK-for-NET. I'm closing this issue here and issues related to AWS Assembly would now be tracked from https://github.com/aws/aws-sdk-net/issues
