### ISSUE TITLE
SerializationException when running dynamodb unity example

### ISSUE THREAD

**Issue by dan335** [aws/aws-sdk-unity#54]
When I run the DynamoDB Unity examples I get ERROR: 400 Bad Request.  When I run the curl that it outputs I get.

    {"__type":"com.amazon.coral.service#SerializationException"}

I have the Cognito example working without errors.  I'm using unity 5 but I added a sqlite3.dll to get around the error.  I did the steps that I found here to create the bookstore table.  http://docs.aws.amazon.com/mobile/sdkforunity/developerguide/dynamodb.html

I also tried creating a table called ProductCatalog but get the same error.

**Comment by karthiksaligrama** [comment]
can you let us know which version of the sdk are you tring to use? Is it from master or the sdk.improvements branch?

**Comment by dan335** [comment]
I downloaded it from here.  http://aws.amazon.com/mobile/sdk/  1.0.5 I think.

**Comment by karthiksaligrama** [comment]
can you tell me steps to reproduce this? Do you have some sample code that you can send to reproduce this problem. My email id is saligram@amazon.com

**Comment by karthiksaligrama** [comment]
can you also try with the latest version of the sdk and let us know if it fixes the problem

**Comment by karthiksaligrama** [comment]
@dan335 closing this issue assuming the update resolved the problem. Please open it again in case it didnot
