### ISSUE TITLE
Doubt/Advice: Downloading AssetBundles using GetObjectAsync takes huge amount of ram!

### ISSUE THREAD

**Issue by NeoAnderson87** [aws/aws-sdk-unity#55]
Downloading asset bundles as mentioned above from S3 takes huge ram , equivalent to uncompressed form of the bundle , why is that and can it be avoided?

**Comment by weijiamao** [comment]
Thank you for your feedback. Can you give us steps to re-produce this issue ? We will dive deeper into this.

**Comment by NeoAnderson87** [comment]
So , AssetBundles (extension .unity3d) are basically a package with compressed assets in them.Unity uses LMZA compression for this. 
if you upload a compressed asset bundle on s3 and try to download it using GetObjectAsync it takes huge amount of ram , basically equivalent to the uncompressed size of the whole package , which is big issue on mobile devices.

 I am right now using a different approach , by even zipping the asset bundle again , uploading the zip to s3 and then downloading the zip (which doesn't causes the said issue) and then unzipping the package at run time on device.

**Comment by weijiamao** [comment]
Hi, can you try this on SDK 2.0.0.0 ?

**Comment by weijiamao** [comment]
Hi, can you still have this issue on Unity 2.0.0.3 ?

**Comment by DaleEmrose** [comment]
I find downloading anything with reasonable size using GetObjectAsync take a huge amount of ram.
It was easy to reproduce, I just setup the S3 Example with a mp4 video to download using GetObjectAsync that was around 90mb. Once it has finished retrieving it from my bucket, the unity ram consumption spikes by around 500mb+! this is using the latest AWS SDK for Unity 2.1.0.0 on OSX in the editor.

**Comment by karthiksaligrama** [comment]
This is something related to the WWW underlying client, I would suggest that you try the new UnityWebRequest api supported in the unityv3 sdk. You can find more information @ https://github.com/aws/aws-sdk-net
