### ISSUE TITLE
Getting Bad Request in Table.Query

### ISSUE THREAD

**Issue by AlexanderSilvaB** [aws/aws-sdk-unity#56]
Hi! I'm working on an app using the aws-sdk-unity and in most cases it works as expected, perfectly. My problem is that when I use Table.Query it always return a Bad Request error. If I try Table.Scan it works, but that's not the best solution for me. 
Here's a piece of my code:

QueryOperationConfig config = new QueryOperationConfig();
config.ConsistentRead = false;
config.Select = SelectValues.AllAttributes;
QueryFilter queryFilter = new QueryFilter();
Document doc = new Document ();
doc.Add("Value", (int) 5);
DynamoDBEntry entry = doc["Value"];
queryFilter.AddCondition("Id", QueryOperator.LessThanOrEqual, entry);
config.Filter = queryFilter;
config.Limit = 1;
Search search = DataTable.Query(config);
List<Document> documentList = new List<Document>();
do
{
    documentList = search.GetNextSet();
   ....
} while(!search.IsDone);

Thank you!

**Comment by karthiksaligrama** [comment]
can you let us know which version of the sdk are you trying to use? Is it from master or the sdk.improvements branch?

**Comment by AlexanderSilvaB** [comment]
I'm using the version 1.0.5. It is from master.
I tried to execute the curl string returned and this message appears:
 {"__type":"com.amazon.coral.service#SerializationException"}

**Comment by karthiksaligrama** [comment]
can you try with the new version of the sdk and let us know if the problem persists?

**Comment by AlexanderSilvaB** [comment]
Ok, I'm implementing testing the new sdk right now and will post a response as soon as I can.
Thank you for the support!

**Comment by karthiksaligrama** [comment]
@AlexanderSilvaB  wanted to follow up and see if the update resolved the problem?

**Comment by AlexanderSilvaB** [comment]
I'm sorry for the delay. After update I noticed that my problem was not solved and then I read the DynamoDB documentation again. What I discovered is that I was doing a wrong request, I was using Table.Query with a non Hash or Range key and then my response was always bad. Reading a bit more I could do exactly what I wanted using Table.Scan.
Thank you very much for your support.
