### ISSUE TITLE
Compile for Windows Phone 8 or Windows Store

### ISSUE THREAD

**Issue by AlexanderSilvaB** [aws/aws-sdk-unity#57]
I'm trying to compile my app witch uses the aws-sdk-unity for Windows Phone 8 or Windows Store but it always fails. The compiler always find errors in the sdk. Does someone knows how to solve it?

Thanks!

**Comment by weijiamao** [comment]
Thanks for your feedback. Unfortunately, we are using some .NET API which is not supported on Windows phone 8. We are evaluating Windows phone 8 support. Your suggestion is very helpful to us.

**Comment by AlexanderSilvaB** [comment]
Ok, thanks!
The sdk is supported for Windows Store apps?

**Comment by weijiamao** [comment]
Hi, now we don't support Windows Store. We are evaluating this feature.

**Comment by AlessandroLacroce** [comment]
We'd like to export to Windows Phone too! Do you have an ETA on it? 

Thanks

**Comment by AlexanderSilvaB** [comment]
You have date for a possible release a compatible version?
Thank you!

**Comment by weijiamao** [comment]
Hi, we are evaluating this feature request. But sorry,  we cannot give a promised release date.

**Comment by karthiksaligrama** [comment]
Moved to feature requests https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
