### ISSUE TITLE
How to tell is someone had previously been socially connected, and how to reliably, safely get a user's identityId

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-unity#59]
If a user *was* connected via a social platform, like Facebook, for instance, but then their access token expired, so they're no longer logged in, they obviously can't properly use Cognito Identity.  If we push through trying to startup, and then sync to get their profile, we get tons of `forbidden` errors, obviously.

I'd love some advice on this from you guys as to what to actually do in this instance.  When they were socially connected, but now no longer are (and we don't want to force them to have to log in again, that's always got to be user's choice).  We were going to handle it by wiping their profile completely, and kind of starting afresh, with no previously stored Cognito information, as if they're a brand new user.

On top of that, I'm currently getting some grief from the SDK to simply get a user's identityId.  We use this as the ids of objects that get stored up on S3, but when I call `credentials.GetIdentityId()`, I get a load of "Network on Main Thread" errors.  The documentation, http://docs.aws.amazon.com/mobile/sdkforunity/developerguide/cognito-identity.html says you're able to do just `String *cognitoId = credentials.identityId;` but the identityId field is private, so obviously that's not correct.

**Comment by karthiksaligrama** [comment]
For getting the identity id you can use the async api. credentials.GetIdentityIdAsync(). We will correct the doc. Thanks for the feedback.

**Comment by seaders** [comment]
And the other bits?  How to know if someone had cached credentials that had been authenticated with a login provider?  (But now obviously don't).  And just advice in general about how to deal with that.  A full clear?

**Comment by albertvaka** [comment]
As of now, you will have to keep track manually of fact that the user did authenticate or did not (eg: store it in the PlayerPrefs). It looks like something that the SDK could do for you, though, so thanks for bringing this up.

**Comment by seaders** [comment]
Ok, but if someone had previously connected, with say Facebook, and we kept track of it, we know that they *were* logged in, but now aren't, if we don't do anything and try to let them connect again, cognito's process will fail because it'll use the last identityId will need a valid access token from Facebook to authenticate, but we won't have one.

You've got to have a suggestion as to what to do in this situation here, no?  I mean from our side, we don't want to wipe someone's profile just because they disconnected our app, or something like that (say they mistakenly did it, if they didn't recognise the game when on Facebook on their desktop), but we have to do something about ensuring they get a non-socially connected identityId.  And from the SDK now, there's more than a few different "Clear" options... so which should it be?  And when?  Before CognitoId creation?  After?  Is there a static method?

**Comment by hgray** [comment]
Adding on to this conversation, I'm finding a few head scratchers in the new 2.0 code related to credentials

1) Without too much difficulty, I ended up with multiple identities stored in player prefs. Is this normal? Shouldn't it be cleaning up old ones?

2) I'm using the sample Cognito Sync project to test out some things. When I have previously logged in, but I restart and hit "Skip Authentication" I see several exceptions thrown by AWS, but I can't catch them. They are triggered by the refresh request in "LoadFromDataset", but it never calls the callback. Can you make sure it bubbles up so we can at least check for it and perform a credentials.Clear() ?

Thanks

**Comment by seaders** [comment]
@albertvaka @karthiksaligrama Any more insight / advice about what to do with the credentials client created, in terms of handling this error if it occurs that someone who was connected to Facebook no longer is?

**Comment by albertvaka** [comment]
@hgray You can end up with more than one identity as long as they are for different different identity pools, but you shouldn't be able otherwise (storing a new one will override the old one). About the second point, it's probably an error, I'm going to have a look at it.

@seaders A user that has once authenticated with Facebook won't be able to login as an authenticate identity again. In most cases this is not a problem because the Facebook SDK will log you in without asking for a password every time you open the app, but it can be an problem if the user actually removed the app permissions from Facebook and you want to give him an unauthenticated identity again. If this is the case you are worried about, I'm afraid that the SDK won't solve it as of now, and you will need to implement it yourself. The flow would be something like: Get the data from the local storage, call Clear in the Cognito client, get a new unauthenticated identity and store the data back.

**Comment by hgray** [comment]
Thanks, I realized that after I looked more closely at the keys. Thanks for looking into #2.

**Comment by karthiksaligrama** [comment]
Revisiting this the documentation now looks good and shows the right API. marking this issue as closed.Please reopen or log another issue if you need more clarifications
