### ISSUE TITLE
Namespace ambiguity

### ISSUE THREAD

**Issue by djsell** [aws/aws-sdk-unity#6]
The Cognito package failed to compile when I first imported it into my project.  The errors were as follows:
```
Assets/AWSUnitySDK/AWSCore/AWSConfigs.bcl.cs(72,20): error CS0117: `Logger' does not contain a definition for `ClearLoggerCache'
Assets/AWSUnitySDK/AWSCore/AWSConfigs.bcl.cs(102,20): error CS0117: `Logger' does not contain a definition for `ClearLoggerCache'
Assets/AWSUnitySDK/AWSCore/Amazon.Runtime/AbstractWebServiceClient.cs(153,38): error CS0117: `Logger' does not contain a definition for `EmptyLogger'
Assets/AWSUnitySDK/AWSCore/Amazon.Runtime/AbstractWebServiceClient.cs(155,38): error CS0117: `Logger' does not contain a definition for `GetLogger'
```

This was a problem because Logger is a very common name for a class, and I already had my own Logger class in the global namespace.  While this happened for me with Logger, I'm sure that there are other classes that will be just as vulnerable (though not as likely).

**Comment by weijiamao** [comment]
Thank you for reporting this issue. In the place of name conflict, please use full namespace reference.

**Comment by hgray** [comment]
Another one is "StringUtils". I have run into similar issues with a conflict with one of our classes of the same name.
