### ISSUE TITLE
Cognito Timeouts do nothing?

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-unity#61]
Full example project -> https://github.com/SixMinute/CognitoTimeouts

Code (https://github.com/SixMinute/CognitoTimeouts/blob/master/Assets/Scripts/TestAWS.cs):

	TimeSpan TS_TIMEOUT = new TimeSpan(0, 0, 1);

	this._credentials = new CognitoAWSCredentials(
		identityPoolId: IDENTITY_POOL_ID, accountId: null,
		unAuthRoleArn: null, authRoleArn: null,
		cibClient: new AmazonCognitoIdentityClient(
			new AnonymousAWSCredentials(),
			new AmazonCognitoIdentityConfig
				{ Timeout = TS_TIMEOUT, RegionEndpoint = COGNITO_REGION }
		),
		stsClient: new AmazonSecurityTokenServiceClient(
			new AnonymousAWSCredentials(),
			new AmazonSecurityTokenServiceConfig
				{ Timeout = TS_TIMEOUT, RegionEndpoint = COGNITO_REGION }
		)
	);

	DateTime before = DateTime.Now;
	Debug.Log("Time before: " + before);
	this._credentials.GetCredentialsAsync(
		_result => {
			Debug.Log( "Time after: " + DateTime.Now + ", duration: " + (DateTime.Now - before) );
			
			Debug.Log(_result);
			if(null != _result.Exception)
			{
				Debug.LogException(_result.Exception);
				return;
			}
			Debug.Log(_result.Response);
			Debug.Log( this._credentials.GetIdentityId() );
		}
	);

Unfortunately, while testing with Network Link Conditioner (https://developer.apple.com/downloads/index.action?q=Network%20Link%20Conditioner#), I'm expecting an error and timeout to occur if we pass over 1 seconds, however how it actually looks, and proved with the key log (https://github.com/SixMinute/CognitoTimeouts/blob/master/Logs/CognitoId.log) bits is,

    Time before: 05/22/2015 15:41:32
    ...
    Time after:  05/22/2015 15:41:37, duration: 00:00:05.5019740

Which obviously shouldn't have been allowed to occur.

If I prevent all network activity,

    Time before: 05/22/2015 16:11:57
    ...
    Time after:  05/22/2015 16:12:28, duration: 00:00:30.6701330

The timeout is obviously 30 seconds.  When I search the source code for '30', there's references that *might* have something to do with something at RegionEndpoint.cs, AWSPublicIpAddressRanges.cs and DefaultRetryPolicy.cs (https://github.com/aws/aws-sdk-unity/blob/62e4a31f06e030e4df81668ba2f811acbea0ad07/Assets/AWSSDK/src/Core/RegionEndpoint.cs, https://github.com/aws/aws-sdk-unity/blob/62e4a31f06e030e4df81668ba2f811acbea0ad07/Assets/AWSSDK/src/Core/Amazon.Util/AWSPublicIpAddressRanges.cs and https://github.com/aws/aws-sdk-unity/blob/62e4a31f06e030e4df81668ba2f811acbea0ad07/Assets/AWSSDK/src/Core/Amazon.Runtime/Pipeline/RetryHandler/DefaultRetryPolicy.cs), but even changing every reference of 30 to 1 there... also did nothing :(

So what's the story?  Am I wrong, is it implemented wrong, or is something else incorrect here?

**Comment by karthiksaligrama** [comment]
WWW does not support timeout. so this particular feature is still in works.

**Comment by seaders** [comment]
Dear oh dear, I'm getting more and more disappointed with Unity with every passing day that I use it. :(

**Comment by karthiksaligrama** [comment]
We are planning to bring in more support for http operations in unity as we go. But as of now we cannot support timeout's.

I'm closing this issue. Is you have any  other questions feel free to comment or open it again.
