### ISSUE TITLE
Build errors in the webplayer version

### ISSUE THREAD

**Issue by LancelotBleu** [aws/aws-sdk-unity#63]
There are build errors in the 2.0 upgrade with the WebPlayer version.

Assets/AWSSDK/src/Core/_unity/AWSConfigs.unity.cs(25,18): error CS0234: The type or namespace name `Linq' does not exist in the namespace `System.Xml'. Are you missing an assembly reference?

Switch to the webplayer build using :  File -> Build Settings -> WebPlayer.

If the Webplayer build is not supported, is there any way to make it compile correctly?

**Comment by karthiksaligrama** [comment]
webplayer is currently not supported in sdk. However you can try manually adding the System.XML.Linq.dll in the project folder. doing this only might get rid of the linq related compilation errors, however the sdk uses other features like FileIO, SQLite which may still not be supported in webplayer (mainly the Cognito Sync Manager & Mobile Analytics Manager).

**Comment by karthiksaligrama** [comment]
the web player plugin is being phased out and hence will not be supported by browsers themselves. as such unity sdk will not support webplayer.

refer http://blogs.unity3d.com/2015/10/08/unity-web-player-roadmap/
