### ISSUE TITLE
ThreadStateException: Thread has already been started. (Mobile Analytics)

### ISSUE THREAD

**Issue by 5argon** [aws/aws-sdk-unity#64]
Often times, I got this error which will repeat it self constantly. Closing-open Unity can solve this but sometimes it came back.

ThreadStateException: Thread has already been started.
System.Threading.Thread.Start () (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Threading/Thread.cs:834)

Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.BackgroundRunner.StartWork () (at Assets/AWSSDK/src/Services/MobileAnalytics/Custom/_unity/BackgroundRunner.cs:59)
Amazon.MobileAnalytics.MobileAnalyticsManager.MobileAnalyticsManager.GetOrCreateInstance (Amazon.Runtime.AWSCredentials credential, Amazon.RegionEndpoint regionEndpoint, Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.ClientContextConfig clientContextConfig) (at Assets/AWSSDK/src/Services/MobileAnalytics/Custom/_unity/MobileAnalyticsManager.cs:166)
Amazon.MobileAnalytics.MobileAnalyticsManager.MobileAnalyticsManager.GetOrCreateInstance (Amazon.Runtime.AWSCredentials credential, Amazon.RegionEndpoint regionEndpoint, System.String appId) (at Assets/AWSSDK/src/Services/MobileAnalytics/Custom/_unity/MobileAnalyticsManager.cs:66)
DOAWS.get_AnalyticsManager () (at Assets/-Common/Scripts/DataSystem/DOAWS.cs:64)
AmazonAnalytics.OnApplicationFocus (Boolean focus) (at Assets/-Common/Scripts/AmazonAnalytics.cs:27)
UnityEditorInternal.InternalEditorUtility:OnGameViewFocus(Boolean)
UnityEditor.HostView:OnFocus()

**Comment by weijiamao** [comment]
Thank you for reporting this issue. We are working on fixing it.

**Comment by weijiamao** [comment]
Hi, we have fixed it in AWS SDK for Unity 2.0.0.4
