### ISSUE TITLE
Can't integrate cognito with facebook sdk

### ISSUE THREAD

**Issue by AlexanderSilvaB** [aws/aws-sdk-unity#65]
I'm trying to integrate the facebook sdk with cognito but everytime I add the facebook login to my credentials the credentials stop being valid, if I try to do any other request I get "No valid credentials found in LocalStorage" and it just works again if I call "ClearCredentialsAndIdentity" from my credentials. If I go the Identity Browser in Identity Pool the Identity is there but there's no linked logins for it.

I'm following this tutorial:
http://docs.aws.amazon.com/cognito/devguide/identity/external-providers/facebook/

Thank you in advance!

**Comment by karthiksaligrama** [comment]
What version of sdk are you using?
When you make a call to credentials.AddLogin with a provider, then the credentials and identity gets cleared by the sdk. However when you make future calls to get the credentials the sdk should automatically fetch the new identity and credentials and cache them.

**Comment by AlexanderSilvaB** [comment]
Thank you!
It works. I was using an old version, with 2.0.0.0 it works perfectly.
