### ISSUE TITLE
AWS in Unity for Windows 7 game, with c#

### ISSUE THREAD

**Issue by chris-hndz** [aws/aws-sdk-unity#67]
Hi all!
I want to develop a game in Unity for Windows 7 in C#, and I want to use the Amazon WS in this game.
Can I use the Amazon WS Unity SDK? Or this SDK is only for mobile plattforms?
How can I have the AWS in a Unity developed game for Windows, with c#?
Thanks!

Best Regards,

Chris.

**Comment by weijiamao** [comment]
We don't have official support to Windows 7. So far our SDK is for Mobile platform. . We are considering to add Windows 7 support.  Thank you for your feedback.

**Comment by karthiksaligrama** [comment]
Moved to feature requests https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
