### ISSUE TITLE
Question: Is there a way one can get information regarding how much of an Object has been downloaded?

### ISSUE THREAD

**Issue by NeoAnderson87** [aws/aws-sdk-unity#68]
So we have to show a progress bar for the download of every s3 Object. How can this be achieved? Currently the callback is fired after the async operation has been completed.

**Comment by karthiksaligrama** [comment]
The SDK doesn't support progress yet. BUt i understand that it can be useful to have it. I'll add it to feature requests for now.

**Comment by umeraftab** [comment]
Is there any expected date for the availability of this feature? Actually I'm running out of time. 
Else for now, is there any way to get the current downloaded bytes of the object?

**Comment by karthiksaligrama** [comment]
at the moment we do not have any time line for this feature. If you want to get the current downloaded bytes of the object then you will have to customize the UnityMainthreadDispatcher.cs and have an event handler to send you http progress.

**Comment by DaleEmrose** [comment]
Heres my solution for download progress using the S3Example files:

modifying UnityMainThreadDispatcher.cs

    //place this above/before public void Awake()
    public delegate void MyEventHandler(string foo);
    public static event MyEventHandler DownloadProgress;

    //place this above/before yield return request.WwwRequest; inside of IEnumerator InvokeRequest(UnityWebRequest request)
    if (request.RequestContent == null) { // only show if downloading the file!
        int prevProgress = 0;
        int currentProgress = 0;
        do {
            currentProgress = ((int)Mathf.Ceil (request.WwwRequest.progress*100f));
            if (prevProgress != currentProgress) {					
                DownloadProgress((currentProgress+"%").ToString());
            }
            prevProgress = currentProgress;
            yield return 0;
        } while (request.WwwRequest.progress < 1);
    }

modifying S3Example.cs

    //place this inside of void Start()
    Amazon.Runtime.Internal.UnityMainThreadDispatcher.DownloadProgress += showDownloadProgress;

    //create a new void function
    void showDownloadProgress(string input) {
        print (input);
    }

Now if I can only figure out why ram is consumed at a ridiculous rate using the GetObjectAsync for larger files... but that's a separate issue...

**Comment by umeraftab** [comment]
Thank you DaleEmrose, it will certainly help me.
Yes, I'm also facing this ram consumption issue. Even sometimes my app getd crashed. I'm wondering if there is some remedy to this issue.

**Comment by NeoAnderson87** [comment]
I guess i can help with this issue. I also posted an issue regarding this long back (The ram issue). I still can't confirm it , but what i guess is happening is that , GetObjectAsync while downloading an object is expanding the compressed file formats.In my case i was downloading compressed unity asset bundles from s3, but they were getting expanded while downloading and the ram usage shot up. The solution i did was , added by own script to the asset bundle script , which compress the the unity package into a zip , and i'll upload that zip on s3. After downloading the zip via GetObjectAsync , i had a script to unzip it at the runtime. This fixed my ram usage issue.

**Comment by PLockhart** [comment]
When queuing a lot of requests, I wanted to keep track of a specific post request. I added code in #107 to add a callback to post requests so you can watch over the web request object, in case anyone finds it useful

**Comment by karthiksaligrama** [comment]
Moved to feature request https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
