### ISSUE TITLE
Multiple identity changes on id creation

### ISSUE THREAD

**Issue by hgray** [aws/aws-sdk-unity#69]
Just a heads up for you all...

In the CharacterSelection demo, I've added an event listener to credentials identity changed event:
credentials.IdentityChangedEvent += HandleIdentityChanged;

When I create a new identity, the handler is fired three times and is showing two different ids:
new_id_1
new_id_2
new_id_1

No biggie, just wanted you all to be aware.

**Comment by albertvaka** [comment]
Does this happen every time? It might happen that you actually have two identities and it's merging them, but that should only happen once.

**Comment by hgray** [comment]
It seems to be happening every time. I did have two identities in my player prefs, but have since cleared them out.

Steps to reproduce:
- Login with FB
- Logout
- Stop Unity
- Delete cognito database
- Confirm prefs file has no identities
- Restart Unity
- Skip Authentication

Incidentally, something else odd is happening in this flow. I'm ending up with several datasets in my database. Where is that coming from for a new unsynced identity?

**Comment by hgray** [comment]
I found the reason: I was calling credentials.GetCredentialAsync() at the end of init(). Maybe it's overlapping requests? I guess I should use the synchronous call once the identity change has been triggered?

**Comment by hgray** [comment]
I was trying to confirm credentials after a login (unauthenticated or authenticated) by calling the GetCredentialAsync() and then checking the exception/result. This leads to the above issues. I have removed that for now and confirmed that the identity isn't created twice.

However, the question is how can we confirm valid credentials?

Follow these steps in the demo project:
- Sign in with Facebook
- Stop the app and restart
- Skip authentication

What ends up happening is a previously authenticated ID is stored in cache, but as I didn't pass in a token, it fails. The problem is that we don't know it has failed until a dataset tries to sync.

Other things I've tried:
- Listening for identity changed event. I find that this fires every time I sign in through Facebook, but only once when a new unauthenticated id is generated
- Checking for cached identity prior to calling GetCredentialAsync(). This resolves the issue above as it will only be called if an identity has already been cached, but it seems like a hack. And it gets confusing when I have to juggle cached identities and multiple event handlers to find what the current state is.

So, I guess what I'm asking is whether we can resolve the above issue so that we can use something like GetCredentialAsync() to confirm a valid credential exists prior to attempting a sync.

**Comment by hgray** [comment]
I've found that waiting for the response to GetCredentialsAsync() before calling a synchronize serves my purpose and doesn't cause the multiple identities.

**Comment by albertvaka** [comment]
Reopening because it's something that we probably want to fix.

**Comment by karthiksaligrama** [comment]
Fixed in version 2.0.0.5
