### ISSUE TITLE
AWSPrefab/AmazonInitializer

### ISSUE THREAD

**Issue by hgray** [aws/aws-sdk-unity#7]
There seem to be places in the code which require the AmazonInitializer. I see that Credentials doesn't require the script, which is great, but I'm finding SQLiteKVStore.cs is trying to pull the AmazonInitializer.persistentDataPath even if I have generated Credentials without using the AmazonInitializer.

It'd be great if we could handle all data during setup through constructor args rather than requiring the script.

**Comment by weijiamao** [comment]
Thank you for your feedback. So far in our design, `AmazonInitializer` is required and it's loaded from `AWSPrefab`. `AmazonInitializer` can read hooked platform info from Unity Engine for later use( Unity engine API can only be called from main thread and you might need those info from any thread) and even more importantly, kick off `AmazonMainThreadDispatcher`.

**Comment by hgray** [comment]
Thanks for the quick response. I realize why you took this approach, and it definitely makes it easier for doing quick prototyping and such, but imagine a scenario where we want to have data stored in two different identity pools at the same time. Maybe we have a single mobile app which contains multiple games and we want each game to store data in a different identity pool. Or maybe the HUD stores data in a "global" pool while each game stores in its own pool. With the current setup, there can only be one AmazonInitializer and therefore we'd not be able to have multiple concurrent instances of AWS writing to different pools. If we were able to create instances and inject the credentials/paths/regions that we needed for each, we could maintain the different pools within a single app.

By the way, I found that there were many other places that required the AmazonInitializer, not just SQLiteKVStore. I was hoping I could modify that one script to get around the issue for testing, but it popped up again in many other places.

**Comment by weijiamao** [comment]
Thanks for reporting this issue. We assumed customer need single identity pool in their game. Your use case is very valuable and we are diving deeper on this.  Your feedback will help us prioritize the features we add in next release.

**Comment by hgray** [comment]
While you're at it, it might be nice to be able to define the path to the database so we could store it where we want. For example, we may want to manage a separate database per user on a device. Thanks again for looking into this.

**Comment by weijiamao** [comment]
Thank you for reporting this issue. We are working on it. Please remember we are in developer preview. Your feedback is very helpful for us to improve Unity SDK.

**Comment by weijiamao** [comment]
Hi, we added multiple Cognito identity pool support in version 1.0.1. 
Please check it.

**Comment by hgray** [comment]
Awesome, thanks!
