### ISSUE TITLE
Exception thrown in Mobile Analytics Delivery Client if Metrics param is named "Count"

### ISSUE THREAD

**Issue by Blundig** [aws/aws-sdk-unity#71]
Creating a custom event with a Metric named "Count" will result in an exception when the client attempts to deliver the event.  (This perhaps happens for Attributes too, but I didn't check).

For example, the following event:

<code>
Event string is {"Attributes":{},"EventType":"FriendsCount","Metrics":{"Count":1.0},"Session":{"Duration":0,"Id":"50696ea5-b985-48af-8df7-5d395b208387","StartTimestamp":"2015-06-10T18:36:18Z","StopTimestamp":null},"Timestamp":"2015-06-10T18:36:20.449Z","Version":"v2.0"}</code>

Will cause this error in the log file:

<code>
Can't assign value '1' (type System.Double) to type System.Int32
</code>
<code>
An exception occurred in Mobile Analytics Delivery Client.
</code>

The exception is thrown from JsonMapper when converting the event string to an Amazon.MobileAnalytics.Model.Event object at line 205 of DeliveryClient.cs. 

The problem is a conflict with the exact parameter name "Count".  If you rename it to something else ("Tally" or "count" with lowercase), the event send will be successful.

On a side note, when an exception occurs during delivery like this, it appears to keep all pending custom data from ever being sent to the backend (including events that do not have any errors).   The client tries sending sending the same data during the next send cycle and encounters the same error.  If this happened in a production app, maybe no more events would be sent until the user reinstalled?

**Comment by weijiamao** [comment]
Thanks for reporting this bug. We are fixing it.

**Comment by karthiksaligrama** [comment]
closed in 2.1.0.0
