### ISSUE TITLE
AWS SDK is causing Unity editor to lock up intermittently

### ISSUE THREAD

**Issue by benbritten** [aws/aws-sdk-unity#73]
This seems like the same issue as https://github.com/aws/aws-sdk-unity/issues/58 

I can't re-open that one, so I am making a new issue, feel free to delete this and reopen that one, or whatever.

In any case:
on 5.1.1p2 and 5.1.1p3 and sdk 2.0.2 we experience crippling lockups in the editor.  We removed all traces of the AWS SDK and stubbed out all code that called to it two days ago and the problems went away. The lockup are intermittent so they are really hard to reproduce, but evidence suggests that it is the AWS SDK causing the problem.

It feels like some sort of threading/race condition, but that is just a guess really.

We are going to try out 5.1.1p4 and sdk 2.0.2 and see if the problem persists, but at this time I am not very hopeful as it seems to be an issue with the SDK and not unity.

**Comment by benbritten** [comment]
I should add that it seems like the unity lockups happened whenever I had played the game and we did some cognito transactions, then stopped the game, went to make some code changes outside of unity, and then upon coming back to unity, during the re-import phase where unity recompiles all the scripts, that is when we would get the beachball of doom most consistently.

**Comment by seaders** [comment]
@benbritten Definitely make sure to log an official Unity bug as well (if you haven't already).  While the AWS SDK is unfortunate in the way that it uses threads causes a lot of Unity's issues to come to the fore, the issues certainly lie with Unity themselves, and how they deal with threads in the Editor.  Worse again when you're trying to debug with these.

**Comment by benbritten** [comment]
@seaders yeah, good call. I'll drop one into the system and also chat with a few of the Unity guys I know.

**Comment by karthiksaligrama** [comment]
@benbritten does the problem get fixed when you use 2.0.0.3? i added the check mentioned in #58 but it could be unrelated

**Comment by thoechsmann** [comment]
We have the same problem. I disabled auto reloading of assets in the Unity editor and trigger it manually. Unity does not hang anymore when compiling. But it still hangs very frequently when starting playmode.

**Comment by karthiksaligrama** [comment]
@thoechsmann can you tell me what version of the sdk are you using? are you using 2.0.0.3?

**Comment by thoechsmann** [comment]
2.0.0.3 with Unity 5.1.2f1

**Comment by karthiksaligrama** [comment]
can you tell me what API is causing this problem?

**Comment by thoechsmann** [comment]
We use CognitoAWSCredentials and CognitoSyncManager. Data is synchronized always with SynchronizeOnConnectivity. Credentials have (most of the time) a Facebook login. Currently we directly try to Sync at startup. This does fails due to no fb-token set at that time. Maybe its related?

When I completely disabled the AWS integration, There are no more lockups in play mode or during compiling.

**Comment by karthiksaligrama** [comment]
Closing this issue. Please open a new  issue on https://github.com/aws/aws-sdk-net/issues/ if you continue to face this problem
