### ISSUE TITLE
Ambiguous method call with DynamoDBContext.LoadAsync when using optional parameter

### ISSUE THREAD

**Issue by aaronhoogstraten** [aws/aws-sdk-unity#74]
When using `public void LoadAsync<T>(T keyObject, AmazonDynamoDBCallback<T> callback, AsyncOptions asyncOptions = null)` and not explicitly passing in null for the 3rd parameter, I get the following compile error from Unity (Unity 4.6.6p3): 
```
error CS0121: The call is ambiguous between the following methods or properties: `Amazon.DynamoDBv2.DataModel.DynamoDBContext.LoadAsync<MyDynamoItem>(object, Amazon.DynamoDBv2.AmazonDynamoDBCallback<MyDynamoItem>, Amazon.Runtime.AsyncOptions)' and `Amazon.DynamoDBv2.DataModel.DynamoDBContext.LoadAsync<MyDynamoItem>(MyDynamoItem, Amazon.DynamoDBv2.AmazonDynamoDBCallback<MyDynamoItem>, Amazon.Runtime.AsyncOptions)'
```

Unforunately this may be a Unity specific issue with how optional parameters are handled:
http://forum.unity3d.com/threads/c-ambiguous-methods-works-in-dotnetfiddle-but-not-in-unity.315527/#post-2049952

However, due to its obscurity maybe it's worth specifically working around in the AWS SDK? Maybe implementing an additional LoadAsync that only takes in the first 2 parameters and omits the optional parameters while still instantiating a default AsyncOptions?

**Comment by weijiamao** [comment]
Thank you for reporting this bug. We are looking for solution.

**Comment by karthiksaligrama** [comment]
@aaronhoogstraten  Do you see this problem in unity 5 as well? or just unity 4?

**Comment by aaronhoogstraten** [comment]
@karthiksaligrama We haven't tested our project in 5 yet. It's on my plate to evaluate soon though.

**Comment by weijiamao** [comment]
Hi, this problem can be produced on Unity 4.6 and Unity 5.1. Confirmed with Unity: It's a compiler issue. Unity won't fix it soon. We suggest you explicitly specify parameter.

**Comment by karthiksaligrama** [comment]
Closing this issue. Please open a new issue on https://github.com/aws/aws-sdk-net/issues if you continue to face this problem
