### ISSUE TITLE
Request to change protection level of CognitoAWSCredentials.Logins or provide accessor

### ISSUE THREAD

**Issue by aaronhoogstraten** [aws/aws-sdk-unity#75]
Currently the only way to check to see if a login provider is used is by looking through CurrentLoginProviders but this seems unwieldy compared to doing a Logins.ContainsKey(provider). There are already RemoveLogin and AddLogin methods so a ContainsLogin would makes sense to me as well if you don't want to change the protection level of Logins.

Thanks!

**Comment by karthiksaligrama** [comment]
can you let us know your use case? I'm not really sure why you one would want to check if the login provider is present or not?

**Comment by aaronhoogstraten** [comment]
For example, if a user want's to unlink their Facebook account from my app I would like to validate that `credentials.Logins.ContainsKey("graph.facebook.com")`

**Comment by karthiksaligrama** [comment]
i would not prefer making the logins map public simply because if you accidentally add value directly to the map you bypass clearing the credentials which is why we removed it.

I think you can simply do this to achieve your use case, considering the values in the array can be a maximum of 4-5, so you should not have performance issues.

```
((IList<string>) Cred.CurrentLoginProviders).Contains("graph.facebook.com");
```

 Does that solve your problem?

**Comment by aaronhoogstraten** [comment]
Yes that works fine, I was just hoping for a cleaner method to do so rather then going from Dictionary to string[] to List. I will use that method though if you recommend it.

The other option I was thinking off would be implementing
```
public bool ContainsLogin(string providerName){
    return Logins.ContainsKey(providerName);
}
```

You can close this issue if you want, just a suggestion :).

**Comment by karthiksaligrama** [comment]
added contains login api to 2.0.0.4

**Comment by aaronhoogstraten** [comment]
Thanks!
