### ISSUE TITLE
Service request: SNS

### ISSUE THREAD

**Issue by hgray** [aws/aws-sdk-unity#8]
I'd love to see SNS as the next service into the SDK.

**Comment by Mudeem** [comment]
Thank you for the writing to us. Your feedback is very valuable and will help us prioritize the service we add to the SDK next.

**Comment by Tsunder3** [comment]
We'd like this feature too, thank you

**Comment by AlessandroLacroce** [comment]
Any news about this feature? We are interested in it too.....

**Comment by karthiksaligrama** [comment]
SNS launched with v2.0.0.1

**Comment by hgray** [comment]
Thumbs up!
