### ISSUE TITLE
You should put a warning about using "micro mscorlib"

### ISSUE THREAD

**Issue by 5argon** [aws/aws-sdk-unity#80]
Since AWS uses SHA256 method which is not available in micro mscorlib, you should have a warning somewhere that you cannot do so.

**Comment by karthiksaligrama** [comment]
@5argon Thanks  for the feedback. I'll take a look at it and see if we can add a warning

**Comment by karthiksaligrama** [comment]
We have added sample link.xml configuration in the readme. If you continue to face problems please raise a new issue on our [dotnet sdk repository](https://github/aws/aws-sdk-net)
