### ISSUE TITLE
Cannot switch users using WipeData

### ISSUE THREAD

**Issue by durnurd** [aws/aws-sdk-unity#81]
In our Unity game, you can change users by logging out of Facebook and logging in as a different user. When you log out, your data is wiped using `CognitoSyncManager.WipeData()`

The documentation for this method states:

> Wipes all user data cached locally, including identity id, session
> credentials, dataset metadata, and all records. Any data that hasn't been
> synced will be lost. This method is usually used when customer logs out.

However, it does not appear to be the case that the identity is cleared. When logging in as a different user, I get this error:

    Amazon.CognitoIdentity.Model.NotAuthorizedException: Logins don't match. Please include at least one valid login for this identity or identity pool. ---> 
    Amazon.Runtime.Internal.UnityHttpErrorResponseException: Exception of type 
    'Amazon.Runtime.Internal.UnityHttpErrorResponseException' was thrown

I must call `CognitoAWSCredentials.Clear()` as well for the credentials to actually be cleared.

**Comment by karthiksaligrama** [comment]
@durnurd sorry the documentation is slighlty incorrect. Its not meant to clear the identity and credentials. Alternatively i also think its a good idea to clear the credentials from within the WipeData api. For now You should call CognitoAWSCredentials.clear();

**Comment by karthiksaligrama** [comment]
Fixed in V 2.0.0.5
