### ISSUE TITLE
(Mobile Analytics) The timestamp on the _session.stop event is that of the awakening time, and not the stopping time. 

### ISSUE THREAD

**Issue by rcha** [aws/aws-sdk-unity#82]
The timestamp of the _session.stop event should have the timestamp of the last _session.pause event and not the timestamp of when the app last came to the foreground.

**Comment by weijiamao** [comment]
Hi, thanks for reporting this issue! We are fixing it.

**Comment by noamgat** [comment]
As I mentioned here : https://forums.aws.amazon.com/thread.jspa?threadID=204296&tstart=0
I think the solution is simply to move the code

      // update session info
            lock(_lock)
            {
                _stopTime = currentTime;
            }

To after the event is sent in Session.StopSession()

**Comment by weijiamao** [comment]
Hi, we have fixed it in AWS SDK for Unity 2.0.0.4
