### ISSUE TITLE
QueryAsync<T>

### ISSUE THREAD

**Issue by linithos** [aws/aws-sdk-unity#83]
Hello,

I'm trying to do a QueryAsycn<T> on a Table with a Hash Key and Range Key. But I'm getting an error "Argument can not be null. Parameter name = null".

var search = DBConnect.Context.QueryAsync<T>(hashKey);
search.GetRemainingAsync((result) =>
 {
   List<T> myList = new List<T>();
   myList = result.Result;
}, null);

I've tried the query on other table with a hashkey only and it works the problem is when the primary id is : hash key and range key.

Any help?

thanks

Lina

**Comment by karthiksaligrama** [comment]
Hi Lina,

For Hash and range key, you should use 
```
     Context.QueryAsync<T>(hashvalue,Amazon.DynamoDBv2.DocumentModel.QueryOperator,rangevalues)
```

**Comment by linithos** [comment]
Thank you. =)
