### ISSUE TITLE
saving data android onPause/onResume?

### ISSUE THREAD

**Issue by cataHHH** [aws/aws-sdk-unity#86]
The request to save sync the data on cloud does not work if app is in the background, what should I do if I want to save the data when the users closes the app ? (sends it in background),
Thanks

**Comment by karthiksaligrama** [comment]
i don't think its possible at the moment to do this. Since the Unity Runtime (including all the Monobehaviour scripts) do not execute when the player is in background AFAIK.

**Comment by karthiksaligrama** [comment]
Closing the issue. Please reopen if you have any other questions
