### ISSUE TITLE
Android not sending events.

### ISSUE THREAD

**Issue by nathan-mishler** [aws/aws-sdk-unity#87]
I got the AWS Mobile Analytic to work in the unity editor, but when I build and run on my LG Tribute, it seems to only say "Delivery already in progress, failing new delivery" - it appears it is trying to send but never actually does.

It's an LG Tribute,  android version 4.4.2

**Comment by nathan-mishler** [comment]
Here is some more information, I am getting an error message now, using the log viewer I see...

I/Unity   (3889):  Request metrics: {"properties":{"AsyncCall":"False","ServiceName":"Amazon.CognitoIdentity","ServiceEndpoint":"https://cognito-identity.us-east-1.amazonaws.com/","MethodName":"GetCredentialsForIdentityRequest","RequestSize":"63","StatusCode":"OK","BytesProcessed":"1136","AWSRequestID":"989ec41e-5aff-11e5-8372-bf305ba2bf85"},"timings":{"HttpRequestTime":7622.8132,"ResponseUnmarshallTime":38.1532,"ResponseProcessingTime":64.1105,"ClientExecuteTime":7746.1095},"counters":{}}
I/Unity   (3889):   
I/Unity   (3889):  (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (3889):  
D/InputTransport(960):  channel '4267cf00 com.mundolanugo.mundolanugo/com.werplay.activityhelper.UnityPlayerNativeActivity (server)' : action=ACTION_UP, downTime=27698303961000, eventTime=27698468715000, pointerCount=1
I/Unity   (3889):  NullReferenceException: Object reference not set to an instance of an object
I/Unity   (3889):    at Amazon.Util.CryptoUtilFactory+CryptoUtil.ComputeSHA256Hash (System.Byte[] data) [0x00000] in <filename unknown>:0 
I/Unity   (3889):    at Amazon.Runtime.Internal.Auth.AWS4Signer.SetRequestBodyHash (IRequest request) [0x00000] in <filename unknown>:0 
I/Unity   (3889):    at Amazon.Runtime.Internal.Auth.AWS4Signer.SignRequest (IRequest request, Amazon.Runtime.ClientConfig clientConfig, Amazon.Runtime.Internal.Util.RequestMetrics metrics, System.String awsAccessKeyId, System.String awsSecretAccessKey) [0x00000] in <filename unknown>:0 
I/Unity   (3889):    at Amazon.Runtime.Internal.Auth.AWS4Signer.Sign (IRequest request, Amazon.Runtime.ClientConfig clientConfig, Amazon.Runtime.Internal.Util.RequestMetrics metrics, System.String awsAccessKeyId, System.String awsSecretAccessKey) [0x00000] in <filename unknown>:0 
I/Unity   (3889):    at Amazon.Runtime.Internal.Signer.SignRequest (IRequestContext requestContext) [0x00000] in <filename unknown>:0 
I/Unity   (3889):    at Amazon.Runtime.Internal.Signer.PreInvoke (IExecutionCo
E/Unity   (3889):  An exception occurred in Mobile Analytics Delivery Client.
E/Unity   (3889):   
E/Unity   (3889):  (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
E/Unity   (3889):

**Comment by karthiksaligrama** [comment]
is this something that you face on every android device or is it something that you face only on LG Tribute?

**Comment by nathan-mishler** [comment]
I have two different LG phones that it does it on, but they seem to be different generations. One is LG tribute and one is LG...Cricket?

**Comment by karthiksaligrama** [comment]
Hi can you give the laest version of sdk a shot and see if you are able to reproduce the error?

**Comment by karthiksaligrama** [comment]
Closing this issue. If you still continue to experience the problem feel free to reopen the issue
