### ISSUE TITLE
Checking if an identity token is expired

### ISSUE THREAD

**Issue by thewall01210** [aws/aws-sdk-unity#9]
I was wondering if there was a way to check if a cognito identity token had expired.  We are currently using Cognito to authenticate our users, however, after about 5 minutes of inactivity the user can no longer access AWS services because the token has expired.  This issue appears most often when the user tries to use Cognito Sync to access their dataSet after the app returns from being inactive for a bit.  We have rigged up a method for refreshing the credentials after approximately 5 minutes, but this is not guaranteed to sync up with the tokens expiry time.  I was hoping you might be able to tell me if there was a more accurate way to tell if the token has expired so that we can make sure the user has the proper authentication.

**Comment by turacma** [comment]
Can you clarify your use case? Cognito itself does not support authentication, so I'm curious to know what authentication mechanism(s) you are using? Are you using a public provider or developer authenticated identities?

While the OpenId Connect token returned from Cognito Identity is short lived, the AWS credentials vended have an expiration of 1 hour. The SDK should handle the refresh of these credentials for you, assuming the underlying credentials used when accessing Cognito are still valid.

**Comment by thewall01210** [comment]
Yes, of course.  Sorry for not being clear enough. We are using a public provider for authentication, Facebook to be more specific.  We thought the SDK would handle the refresh as well, however after about 5 minutes of inactivity synchronizing the users dataset fails due to the expiration of an identity token.   Calling refresh after about 4.5 minutes of inactivity will circumvent the problem, but it is not guaranteed.

**Comment by thewall01210** [comment]
Is there a certain amount of time between my application becoming active again and making any calls to the sdk that I should allow for? If so how do I check if the sdk is ready to receive calls?

**Comment by turacma** [comment]
It appears you may be hitting against a bug in SDK. What **should** be happening is that should be able to just set the token of the identity provider you are using (FB) on the logins value of the CognitoAWSCredentials object. You should not need to use IdentityProvider at all for public providers.

We are trying to replicate the issue and diagnose the root cause. Apologies for the inconvenience.

**Comment by thewall01210** [comment]
No worries, I understand that the SDK is in developer preview.  Thanks for all of your help I just wanted to give you as much information about the issue as possible.

**Comment by albertvaka** [comment]
Hi! Is this happening to you on the editor also, or only on an actual device?

**Comment by thewall01210** [comment]
At the stage of development were at we were only testing on device.  I have no idea if its happening in editor or not.

**Comment by albertvaka** [comment]
I can not reproduce the error using the Cognito Sync Sample and leaving the phone with the app running for a while and then trying to sync again. Is there something specific I should do to try to reproduce this?

**Comment by thewall01210** [comment]
Not that I know of It just happens ... The sync ends up working but not before it fails.

**Comment by albertvaka** [comment]
Hi,

We have released a new version of the SDK, could you please upgrade and tell us if the problem is still there in the new version?

Thanks,
Albert

**Comment by thewall01210** [comment]
Yes the issue is fixed in the new version. Thanks!
