### ISSUE TITLE
Cannot implement exponential back-off or error handling

### ISSUE THREAD

**Issue by andreineacsu** [aws/aws-sdk-unity#90]
We cannot implement exponential back-off or error handling as described here (http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ErrorHandling.html#APIRetries) since the SDK doesn't return the JSON containing the exception. We need support for this issue, otherwise it will be extremely hard to handle errors. 
Thank you!

**Comment by karthiksaligrama** [comment]
related to #89 for retries. For the error response This is a known limitation for WWW (across Unity 4.x.x to Unity 5.x.x, though as you mentioned in #89 it might be patched in newer unity releases).

**Comment by karthiksaligrama** [comment]
closed in 2.1.0.0
