### ISSUE TITLE
2.0.0.5 AWSPrefab broken? Can't drag into scene

### ISSUE THREAD

**Issue by aaronhoogstraten** [aws/aws-sdk-unity#93]
I did a fresh import of the 2.0.0.5 DynamoDB and Cognito Sync packages (I removed my 2.0.0.3 folder completely) and now I'm unable to drag the AWSPrefab into the scene/hierarchy. The icon it displays is a blank white page instead of the normal Unity blue prefab cube. I had to revert back to the 2.0.0.3 AWSPrefab and I had to manually fix the missing script reference on it (re-attach UnityInitializer.cs).

**Comment by karthiksaligrama** [comment]
there is no difference between the 2.0.0.3 prefab and 2.0.0.5 prefab so you should be good with solution that you have done. I'll fix this in next release.

**Comment by aaronhoogstraten** [comment]
Ok sounds good!

**Comment by karthiksaligrama** [comment]
closed in 2.1.0.0
