### ISSUE TITLE
Recieved Exception of type InvalidParameterException:, Message No such SyncCount: xx exists for this Dataset

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-unity#94]
This is an intermittent problem we receive, normally on a few problematic devices which we often test with by logging into and out of many different social networks.

Unfortunately, when a device gets into this state, it normally stays this way, no matter what type of wipe you do on it.  I'm unable to track down whether the issue is coming from the servers, or from my device, and any time I try to debug on device through the underlying code, the app just crashes.

	10-07 18:13:04.792: E/Unity(20657): Recieved Exception of type InvalidParameterException:, Message No such SyncCount: 37 exists for this Dataset, request id 
	10-07 18:13:04.792: E/Unity(20657):  
	10-07 18:13:04.792: E/Unity(20657): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

We have a transactional system to users logging in, when they try to login, they get all the way through, or we reverse back to completely unauthenticated.  Due to this, it's imperative we're able to be able to fix issues like the above.

**Comment by albertvaka** [comment]
This happens when the SDK requests from the service a "SyncCount" higher than the one stored server-side. This means that the client has a version of the SDK "newer" than the newest version on the server. 

In any case, the Unity SDK was fixed some months ago to be able to recover from this scenario by replacing its local sync count by the remote one. Are you using a recent version of the SDK?

**Comment by seaders** [comment]
We've been in soft-launch / release for the last month or two, so had only been upgrading SDKs that were *absolutely* necessary, or breaking otherwise.  We're just past that crunch time, so I'll upgrade in the next day or two, and check if that fixes it all.

**Comment by karthiksaligrama** [comment]
i'm closing this issue since its been fixed in the sdk. if you think there is still an issue please reopen or comment below

**Comment by seaders** [comment]
Yeah, all is looking fine with the newest SDK.  Cheers @karthiksaligrama and @albertvaka.
