### ISSUE TITLE
Analytics : session.stop events are missing global attributes and metrics

### ISSUE THREAD

**Issue by noamgat** [aws/aws-sdk-unity#99]
Hi,

We are encountering an issue, that session.stop events sometimes don't carry global attributes and metrics that they were supposed to. After looking into the SDK's code, I think the problem is that the SessionStorage class does not contain the global attributes / metrics when it stores.

So if the flow is Go to background -> Wait for session timeout -> Resume then the global attributes/metrics will be sent, because they still exist in the context.
But if the flow is Go to background -> kill app -> start app then the global attributes / metrics won't be sent.

I think the solution is simple - add the global metrics and attributes to the SessionStorage object.

**Comment by karthiksaligrama** [comment]
Thanks for bringing this up. Will update you when we have a fix. Until then we ask that you reinitialize global event before resume.

**Comment by noamgat** [comment]
Added a pull request that fixes this issue:
https://github.com/aws/aws-sdk-unity/pull/115

**Comment by karthiksaligrama** [comment]
Continuing discussion on #115. Closing this issue
